
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-31T16:58:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf2d0f937202dd91e69ca2c5a9c301be1c108a28",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
