# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bgrafana-api.api.teams_api import TeamsApi  # noqa: E501


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_team_member(self) -> None:
        """Test case for add_team_member

        Add Team Member.  # noqa: E501
        """
        pass

    def test_create_team(self) -> None:
        """Test case for create_team

        Add Team.  # noqa: E501
        """
        pass

    def test_delete_team_by_id(self) -> None:
        """Test case for delete_team_by_id

        Delete Team By ID.  # noqa: E501
        """
        pass

    def test_get_team_by_id(self) -> None:
        """Test case for get_team_by_id

        Get Team By ID.  # noqa: E501
        """
        pass

    def test_get_team_members(self) -> None:
        """Test case for get_team_members

        Get Team Members.  # noqa: E501
        """
        pass

    def test_get_team_preferences(self) -> None:
        """Test case for get_team_preferences

        Get Team Preferences.  # noqa: E501
        """
        pass

    def test_remove_team_member(self) -> None:
        """Test case for remove_team_member

        Remove Member From Team.  # noqa: E501
        """
        pass

    def test_search_teams(self) -> None:
        """Test case for search_teams

        Team Search With Paging.  # noqa: E501
        """
        pass

    def test_update_team(self) -> None:
        """Test case for update_team

        Update Team.  # noqa: E501
        """
        pass

    def test_update_team_member(self) -> None:
        """Test case for update_team_member

        Update Team Member.  # noqa: E501
        """
        pass

    def test_update_team_preferences(self) -> None:
        """Test case for update_team_preferences

        Update Team Preferences.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
