# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bgrafana-api.models.gettable_grafana_rule import GettableGrafanaRule  # noqa: E501

class TestGettableGrafanaRule(unittest.TestCase):
    """GettableGrafanaRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GettableGrafanaRule:
        """Test GettableGrafanaRule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GettableGrafanaRule`
        """
        model = GettableGrafanaRule()  # noqa: E501
        if include_optional:
            return GettableGrafanaRule(
                condition = '',
                data = [
                    bgrafana-api.models.alert_query_represents_a_single_query_associated_with_an_alert_definition/.AlertQuery represents a single query associated with an alert definition.(
                        datasource_uid = '', 
                        model = bgrafana-api.models.model.model(), 
                        query_type = '', 
                        ref_id = '', 
                        relative_time_range = bgrafana-api.models.relative_time_range.RelativeTimeRange(
                            from = 56, 
                            to = 56, ), )
                    ],
                exec_err_state = 'OK',
                id = 56,
                interval_seconds = 56,
                is_paused = True,
                namespace_id = 56,
                namespace_uid = '',
                no_data_state = 'Alerting',
                org_id = 56,
                provenance = '',
                rule_group = '',
                title = '',
                uid = '',
                updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                version = 56
            )
        else:
            return GettableGrafanaRule(
        )
        """

    def testGettableGrafanaRule(self):
        """Test GettableGrafanaRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
