# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bgrafana-api.models.create_playlist_command import CreatePlaylistCommand  # noqa: E501

class TestCreatePlaylistCommand(unittest.TestCase):
    """CreatePlaylistCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePlaylistCommand:
        """Test CreatePlaylistCommand
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePlaylistCommand`
        """
        model = CreatePlaylistCommand()  # noqa: E501
        if include_optional:
            return CreatePlaylistCommand(
                interval = '',
                items = [
                    bgrafana-api.models.playlist_item.PlaylistItem(
                        id = 56, 
                        playlist_id = 56, 
                        order = 56, 
                        title = '', 
                        type = '', 
                        value = '', )
                    ],
                name = ''
            )
        else:
            return CreatePlaylistCommand(
        )
        """

    def testCreatePlaylistCommand(self):
        """Test CreatePlaylistCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
