# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bgrafana-api.models.user_search_hit_dto import UserSearchHitDTO  # noqa: E501

class TestUserSearchHitDTO(unittest.TestCase):
    """UserSearchHitDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSearchHitDTO:
        """Test UserSearchHitDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSearchHitDTO`
        """
        model = UserSearchHitDTO()  # noqa: E501
        if include_optional:
            return UserSearchHitDTO(
                auth_labels = [
                    ''
                    ],
                avatar_url = '',
                email = '',
                id = 56,
                is_admin = True,
                is_disabled = True,
                last_seen_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_seen_at_age = '',
                login = '',
                name = ''
            )
        else:
            return UserSearchHitDTO(
        )
        """

    def testUserSearchHitDTO(self):
        """Test UserSearchHitDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
