# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bgrafana-api.api.get_current_org_api import GetCurrentOrgApi  # noqa: E501


class TestGetCurrentOrgApi(unittest.TestCase):
    """GetCurrentOrgApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetCurrentOrgApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_current_org_quota(self) -> None:
        """Test case for get_current_org_quota

        Fetch Organization quota.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
