# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.

    The version of the OpenAPI document: 0.0.1
    Contact: hello@grafana.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from bgrafana-api.models.admin_stats import AdminStats  # noqa: E501

class TestAdminStats(unittest.TestCase):
    """AdminStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminStats:
        """Test AdminStats
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminStats`
        """
        model = AdminStats()  # noqa: E501
        if include_optional:
            return AdminStats(
                active_admins = 56,
                active_editors = 56,
                active_sessions = 56,
                active_users = 56,
                active_viewers = 56,
                admins = 56,
                alerts = 56,
                daily_active_admins = 56,
                daily_active_editors = 56,
                daily_active_sessions = 56,
                daily_active_users = 56,
                daily_active_viewers = 56,
                dashboards = 56,
                datasources = 56,
                editors = 56,
                monthly_active_users = 56,
                orgs = 56,
                playlists = 56,
                snapshots = 56,
                stars = 56,
                tags = 56,
                users = 56,
                viewers = 56
            )
        else:
            return AdminStats(
        )
        """

    def testAdminStats(self):
        """Test AdminStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
