from typing import Any

class CommandConfigurationEvent:
    def __init__(self, attribute: str, old_value: Any, new_value: Any) -> None: ...
    @property
    def attribute(self) -> str: ...
    @property
    def old_value(self) -> Any: ...
    @property
    def new_value(self) -> Any: ...
