from auto_phylo.pipeliner.model.Command import Command
from typing import Iterable, Iterator, List

class CommandsIterator(Iterator[Command]):
    def __init__(self, commands: Commands) -> None: ...
    def __next__(self) -> Command: ...

class Commands(Iterable[Command]):
    def __init__(self, commands: Iterable[Command]) -> None: ...
    @property
    def commands(self) -> List[Command]: ...
    def list_names(self) -> List[str]: ...
    def find_by_tool(self, tool: str) -> Command: ...
    def find_by_name(self, name: str) -> Command: ...
    def __iter__(self) -> Iterator[Command]: ...
    def __copy__(self) -> Commands: ...
    def __deepcopy__(self, memodict=...) -> Commands: ...
