from typing import Any, Optional

class PipelineConfigurationChangeEvent:
    def __init__(self, attribute: str, old_value: Optional[Any], new_value: Optional[Any]) -> None: ...
    @property
    def attribute(self) -> str: ...
    @property
    def old_value(self) -> Optional[Any]: ...
    @property
    def new_value(self) -> Optional[Any]: ...
