from auto_phylo.pipeliner.model.PipelineChangeType import PipelineChangeType as PipelineChangeType
from typing import Optional

class PipelineChangeEvent:
    def __init__(self, action: PipelineChangeType, index_a: int, index_b: Optional[int] = ...) -> None: ...
    @property
    def action(self) -> PipelineChangeType: ...
    @property
    def index(self) -> int: ...
    @property
    def index_a(self) -> int: ...
    @property
    def index_b(self) -> Optional[int]: ...
