
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-30T07:22:01+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "c97c68808e0c68c5d3d32be92b096f7de37a1c0e",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
