# This file is automatically @generated. DO NOT EDIT!
# fmt: off

from typing import Type, TypedDict

from .payloads import (
    AVRPCMColorSet,
    _AVRPCMColorSetCallable,
    AVRPCMColorTimed,
    _AVRPCMColorTimedCallable,
    AVREmptyMessage,
    _AVREmptyMessageCallable,
    AVRPCMServo,
    _AVRPCMServoCallable,
    AVRPCMServoPWM,
    _AVRPCMServoPWMCallable,
    AVRPCMServoPercent,
    _AVRPCMServoPercentCallable,
    AVRPCMServoAbsolute,
    _AVRPCMServoAbsoluteCallable,
    AVRFCMActionSleep,
    _AVRFCMActionSleepCallable,
    AVRFCMActionTakeoff,
    _AVRFCMActionTakeoffCallable,
    AVRFCMGoToGlobal,
    _AVRFCMGoToGlobalCallable,
    AVRFCMGoToLocal,
    _AVRFCMGoToLocalCallable,
    AVRFCMMissionUpload,
    _AVRFCMMissionUploadCallable,
    AVRFCMHILGPSStats,
    _AVRFCMHILGPSStatsCallable,
    AVRFCMAirborne,
    _AVRFCMAirborneCallable,
    AVRFCMLanded,
    _AVRFCMLandedCallable,
    AVRFCMBattery,
    _AVRFCMBatteryCallable,
    AVRFCMArmed,
    _AVRFCMArmedCallable,
    AVRFCMFlightMode,
    _AVRFCMFlightModeCallable,
    AVRFCMPositionLocal,
    _AVRFCMPositionLocalCallable,
    AVRFCMPositionGlobal,
    _AVRFCMPositionGlobalCallable,
    AVRFCMPositionHome,
    _AVRFCMPositionHomeCallable,
    AVRFCMAttitudeEulerDegrees,
    _AVRFCMAttitudeEulerDegreesCallable,
    AVRFCMVelocity,
    _AVRFCMVelocityCallable,
    AVRFCMGPSInfo,
    _AVRFCMGPSInfoCallable,
    AVRFusionPositionLocal,
    _AVRFusionPositionLocalCallable,
    AVRFusionVelocity,
    _AVRFusionVelocityCallable,
    AVRFusionPositionGlobal,
    _AVRFusionPositionGlobalCallable,
    AVRFusionGroundspeed,
    _AVRFusionGroundspeedCallable,
    AVRFusionCourse,
    _AVRFusionCourseCallable,
    AVRFusionHeading,
    _AVRFusionHeadingCallable,
    AVRFusionClimbRate,
    _AVRFusionClimbRateCallable,
    AVRFusionAttitudeQuaternion,
    _AVRFusionAttitudeQuaternionCallable,
    AVRFusionAttitudeEulerRadians,
    _AVRFusionAttitudeEulerRadiansCallable,
    AVRFusionHILGPSMessage,
    _AVRFusionHILGPSMessageCallable,
    AVRVIOResync,
    _AVRVIOResyncCallable,
    AVRVIOPositionLocal,
    _AVRVIOPositionLocalCallable,
    AVRVIOVelocity,
    _AVRVIOVelocityCallable,
    AVRVIOAttitudeEulerRadians,
    _AVRVIOAttitudeEulerRadiansCallable,
    AVRVIOAttitudeQuaternion,
    _AVRVIOAttitudeQuaternionCallable,
    AVRVIOHeading,
    _AVRVIOHeadingCallable,
    AVRVIOConfidence,
    _AVRVIOConfidenceCallable,
    AVRVIOImageCapture,
    _AVRVIOImageCaptureCallable,
    AVRVIOImageRequest,
    _AVRVIOImageRequestCallable,
    AVRVIOImageStreamEnable,
    _AVRVIOImageStreamEnableCallable,
    AVRAprilTagsVehiclePosition,
    _AVRAprilTagsVehiclePositionCallable,
    AVRAprilTagsRaw,
    _AVRAprilTagsRawCallable,
    AVRAprilTagsVisible,
    _AVRAprilTagsVisibleCallable,
    AVRAprilTagsStatus,
    _AVRAprilTagsStatusCallable,
    AVRThermalReading,
    _AVRThermalReadingCallable,
    AVRAutonomousBuildingEnable,
    _AVRAutonomousBuildingEnableCallable,
    AVRAutonomousBuildingDisable,
    _AVRAutonomousBuildingDisableCallable,
)

MQTTTopics = [
    "avr/pcm/color/set",
    "avr/pcm/color/timed",
    "avr/pcm/laser/fire",
    "avr/pcm/laser/on",
    "avr/pcm/laser/off",
    "avr/pcm/servo/open",
    "avr/pcm/servo/close",
    "avr/pcm/servo/pwm/min",
    "avr/pcm/servo/pwm/max",
    "avr/pcm/servo/percent",
    "avr/pcm/servo/absolute",
    "avr/fcm/action/capture_home",
    "avr/fcm/action/sleep",
    "avr/fcm/action/arm",
    "avr/fcm/action/disarm",
    "avr/fcm/action/kill",
    "avr/fcm/action/land",
    "avr/fcm/action/takeoff",
    "avr/fcm/action/reboot",
    "avr/fcm/action/goto/global",
    "avr/fcm/action/goto/local",
    "avr/fcm/action/mission/upload",
    "avr/fcm/action/mission/start",
    "avr/fcm/hil_gps/stats",
    "avr/fcm/airborne",
    "avr/fcm/landed",
    "avr/fcm/battery",
    "avr/fcm/armed",
    "avr/fcm/flight_mode",
    "avr/fcm/position/local",
    "avr/fcm/position/global",
    "avr/fcm/position/home",
    "avr/fcm/attitude/euler/degrees",
    "avr/fcm/velocity",
    "avr/fcm/gps/info",
    "avr/fusion/position/local",
    "avr/fusion/velocity",
    "avr/fusion/position/global",
    "avr/fusion/groundspeed",
    "avr/fusion/course",
    "avr/fusion/heading",
    "avr/fusion/climb_rate",
    "avr/fusion/attitude/quaternion",
    "avr/fusion/attitude/euler/radians",
    "avr/fusion/hil_gps/message",
    "avr/vio/resync",
    "avr/vio/position/local",
    "avr/vio/velocity",
    "avr/vio/attitude/euler/radians",
    "avr/vio/attitude/quaternion",
    "avr/vio/heading",
    "avr/vio/confidence",
    "avr/vio/image/capture",
    "avr/vio/image/request",
    "avr/vio/image/stream/enable",
    "avr/vio/image/stream/disable",
    "avr/apriltags/vehicle_position",
    "avr/apriltags/raw",
    "avr/apriltags/visible",
    "avr/apriltags/status",
    "avr/status/led/pcm",
    "avr/status/led/vio",
    "avr/status/led/apriltags",
    "avr/status/led/fcm",
    "avr/status/led/thermal",
    "avr/thermal/reading",
    "avr/autonomous/enable",
    "avr/autonomous/disable",
    "avr/autonomous/building/enable",
    "avr/autonomous/building/disable",
]
"""
List of all MQTT topics as strings. This is in no particular order.
"""

MQTTPayloads = [
    AVRPCMColorSet,
    AVRPCMColorTimed,
    AVREmptyMessage,
    AVRPCMServo,
    AVRPCMServoPWM,
    AVRPCMServoPercent,
    AVRPCMServoAbsolute,
    AVRFCMActionSleep,
    AVRFCMActionTakeoff,
    AVRFCMGoToGlobal,
    AVRFCMGoToLocal,
    AVRFCMMissionUpload,
    AVRFCMHILGPSStats,
    AVRFCMAirborne,
    AVRFCMLanded,
    AVRFCMBattery,
    AVRFCMArmed,
    AVRFCMFlightMode,
    AVRFCMPositionLocal,
    AVRFCMPositionGlobal,
    AVRFCMPositionHome,
    AVRFCMAttitudeEulerDegrees,
    AVRFCMVelocity,
    AVRFCMGPSInfo,
    AVRFusionPositionLocal,
    AVRFusionVelocity,
    AVRFusionPositionGlobal,
    AVRFusionGroundspeed,
    AVRFusionCourse,
    AVRFusionHeading,
    AVRFusionClimbRate,
    AVRFusionAttitudeQuaternion,
    AVRFusionAttitudeEulerRadians,
    AVRFusionHILGPSMessage,
    AVRVIOResync,
    AVRVIOPositionLocal,
    AVRVIOVelocity,
    AVRVIOAttitudeEulerRadians,
    AVRVIOAttitudeQuaternion,
    AVRVIOHeading,
    AVRVIOConfidence,
    AVRVIOImageCapture,
    AVRVIOImageRequest,
    AVRVIOImageStreamEnable,
    AVRAprilTagsVehiclePosition,
    AVRAprilTagsRaw,
    AVRAprilTagsVisible,
    AVRAprilTagsStatus,
    AVRThermalReading,
    AVRAutonomousBuildingEnable,
    AVRAutonomousBuildingDisable,
]
"""
List of all MQTT payload classes. This is in no particular order.
There are no duplicates.
"""

_MQTTTopicCallableTypedDict = TypedDict(
    "_MQTTTopicCallableTypedDict",
    {
        "avr/pcm/color/set": _AVRPCMColorSetCallable,
        "avr/pcm/color/timed": _AVRPCMColorTimedCallable,
        "avr/pcm/laser/fire": _AVREmptyMessageCallable,
        "avr/pcm/laser/on": _AVREmptyMessageCallable,
        "avr/pcm/laser/off": _AVREmptyMessageCallable,
        "avr/pcm/servo/open": _AVRPCMServoCallable,
        "avr/pcm/servo/close": _AVRPCMServoCallable,
        "avr/pcm/servo/pwm/min": _AVRPCMServoPWMCallable,
        "avr/pcm/servo/pwm/max": _AVRPCMServoPWMCallable,
        "avr/pcm/servo/percent": _AVRPCMServoPercentCallable,
        "avr/pcm/servo/absolute": _AVRPCMServoAbsoluteCallable,
        "avr/fcm/action/capture_home": _AVREmptyMessageCallable,
        "avr/fcm/action/sleep": _AVRFCMActionSleepCallable,
        "avr/fcm/action/arm": _AVREmptyMessageCallable,
        "avr/fcm/action/disarm": _AVREmptyMessageCallable,
        "avr/fcm/action/kill": _AVREmptyMessageCallable,
        "avr/fcm/action/land": _AVREmptyMessageCallable,
        "avr/fcm/action/takeoff": _AVRFCMActionTakeoffCallable,
        "avr/fcm/action/reboot": _AVREmptyMessageCallable,
        "avr/fcm/action/goto/global": _AVRFCMGoToGlobalCallable,
        "avr/fcm/action/goto/local": _AVRFCMGoToLocalCallable,
        "avr/fcm/action/mission/upload": _AVRFCMMissionUploadCallable,
        "avr/fcm/action/mission/start": _AVREmptyMessageCallable,
        "avr/fcm/hil_gps/stats": _AVRFCMHILGPSStatsCallable,
        "avr/fcm/airborne": _AVRFCMAirborneCallable,
        "avr/fcm/landed": _AVRFCMLandedCallable,
        "avr/fcm/battery": _AVRFCMBatteryCallable,
        "avr/fcm/armed": _AVRFCMArmedCallable,
        "avr/fcm/flight_mode": _AVRFCMFlightModeCallable,
        "avr/fcm/position/local": _AVRFCMPositionLocalCallable,
        "avr/fcm/position/global": _AVRFCMPositionGlobalCallable,
        "avr/fcm/position/home": _AVRFCMPositionHomeCallable,
        "avr/fcm/attitude/euler/degrees": _AVRFCMAttitudeEulerDegreesCallable,
        "avr/fcm/velocity": _AVRFCMVelocityCallable,
        "avr/fcm/gps/info": _AVRFCMGPSInfoCallable,
        "avr/fusion/position/local": _AVRFusionPositionLocalCallable,
        "avr/fusion/velocity": _AVRFusionVelocityCallable,
        "avr/fusion/position/global": _AVRFusionPositionGlobalCallable,
        "avr/fusion/groundspeed": _AVRFusionGroundspeedCallable,
        "avr/fusion/course": _AVRFusionCourseCallable,
        "avr/fusion/heading": _AVRFusionHeadingCallable,
        "avr/fusion/climb_rate": _AVRFusionClimbRateCallable,
        "avr/fusion/attitude/quaternion": _AVRFusionAttitudeQuaternionCallable,
        "avr/fusion/attitude/euler/radians": _AVRFusionAttitudeEulerRadiansCallable,
        "avr/fusion/hil_gps/message": _AVRFusionHILGPSMessageCallable,
        "avr/vio/resync": _AVRVIOResyncCallable,
        "avr/vio/position/local": _AVRVIOPositionLocalCallable,
        "avr/vio/velocity": _AVRVIOVelocityCallable,
        "avr/vio/attitude/euler/radians": _AVRVIOAttitudeEulerRadiansCallable,
        "avr/vio/attitude/quaternion": _AVRVIOAttitudeQuaternionCallable,
        "avr/vio/heading": _AVRVIOHeadingCallable,
        "avr/vio/confidence": _AVRVIOConfidenceCallable,
        "avr/vio/image/capture": _AVRVIOImageCaptureCallable,
        "avr/vio/image/request": _AVRVIOImageRequestCallable,
        "avr/vio/image/stream/enable": _AVRVIOImageStreamEnableCallable,
        "avr/vio/image/stream/disable": _AVREmptyMessageCallable,
        "avr/apriltags/vehicle_position": _AVRAprilTagsVehiclePositionCallable,
        "avr/apriltags/raw": _AVRAprilTagsRawCallable,
        "avr/apriltags/visible": _AVRAprilTagsVisibleCallable,
        "avr/apriltags/status": _AVRAprilTagsStatusCallable,
        "avr/status/led/pcm": _AVREmptyMessageCallable,
        "avr/status/led/vio": _AVREmptyMessageCallable,
        "avr/status/led/apriltags": _AVREmptyMessageCallable,
        "avr/status/led/fcm": _AVREmptyMessageCallable,
        "avr/status/led/thermal": _AVREmptyMessageCallable,
        "avr/thermal/reading": _AVRThermalReadingCallable,
        "avr/autonomous/enable": _AVREmptyMessageCallable,
        "avr/autonomous/disable": _AVREmptyMessageCallable,
        "avr/autonomous/building/enable": _AVRAutonomousBuildingEnableCallable,
        "avr/autonomous/building/disable": _AVRAutonomousBuildingDisableCallable,
    },
    total=False
)
"""
TypedDict of topics as keys, and function signatures that accept the corresponding
payload class as values.
"""

MQTTTopicCallable: _MQTTTopicCallableTypedDict = {
    "avr/pcm/color/set": _AVRPCMColorSetCallable,
    "avr/pcm/color/timed": _AVRPCMColorTimedCallable,
    "avr/pcm/laser/fire": _AVREmptyMessageCallable,
    "avr/pcm/laser/on": _AVREmptyMessageCallable,
    "avr/pcm/laser/off": _AVREmptyMessageCallable,
    "avr/pcm/servo/open": _AVRPCMServoCallable,
    "avr/pcm/servo/close": _AVRPCMServoCallable,
    "avr/pcm/servo/pwm/min": _AVRPCMServoPWMCallable,
    "avr/pcm/servo/pwm/max": _AVRPCMServoPWMCallable,
    "avr/pcm/servo/percent": _AVRPCMServoPercentCallable,
    "avr/pcm/servo/absolute": _AVRPCMServoAbsoluteCallable,
    "avr/fcm/action/capture_home": _AVREmptyMessageCallable,
    "avr/fcm/action/sleep": _AVRFCMActionSleepCallable,
    "avr/fcm/action/arm": _AVREmptyMessageCallable,
    "avr/fcm/action/disarm": _AVREmptyMessageCallable,
    "avr/fcm/action/kill": _AVREmptyMessageCallable,
    "avr/fcm/action/land": _AVREmptyMessageCallable,
    "avr/fcm/action/takeoff": _AVRFCMActionTakeoffCallable,
    "avr/fcm/action/reboot": _AVREmptyMessageCallable,
    "avr/fcm/action/goto/global": _AVRFCMGoToGlobalCallable,
    "avr/fcm/action/goto/local": _AVRFCMGoToLocalCallable,
    "avr/fcm/action/mission/upload": _AVRFCMMissionUploadCallable,
    "avr/fcm/action/mission/start": _AVREmptyMessageCallable,
    "avr/fcm/hil_gps/stats": _AVRFCMHILGPSStatsCallable,
    "avr/fcm/airborne": _AVRFCMAirborneCallable,
    "avr/fcm/landed": _AVRFCMLandedCallable,
    "avr/fcm/battery": _AVRFCMBatteryCallable,
    "avr/fcm/armed": _AVRFCMArmedCallable,
    "avr/fcm/flight_mode": _AVRFCMFlightModeCallable,
    "avr/fcm/position/local": _AVRFCMPositionLocalCallable,
    "avr/fcm/position/global": _AVRFCMPositionGlobalCallable,
    "avr/fcm/position/home": _AVRFCMPositionHomeCallable,
    "avr/fcm/attitude/euler/degrees": _AVRFCMAttitudeEulerDegreesCallable,
    "avr/fcm/velocity": _AVRFCMVelocityCallable,
    "avr/fcm/gps/info": _AVRFCMGPSInfoCallable,
    "avr/fusion/position/local": _AVRFusionPositionLocalCallable,
    "avr/fusion/velocity": _AVRFusionVelocityCallable,
    "avr/fusion/position/global": _AVRFusionPositionGlobalCallable,
    "avr/fusion/groundspeed": _AVRFusionGroundspeedCallable,
    "avr/fusion/course": _AVRFusionCourseCallable,
    "avr/fusion/heading": _AVRFusionHeadingCallable,
    "avr/fusion/climb_rate": _AVRFusionClimbRateCallable,
    "avr/fusion/attitude/quaternion": _AVRFusionAttitudeQuaternionCallable,
    "avr/fusion/attitude/euler/radians": _AVRFusionAttitudeEulerRadiansCallable,
    "avr/fusion/hil_gps/message": _AVRFusionHILGPSMessageCallable,
    "avr/vio/resync": _AVRVIOResyncCallable,
    "avr/vio/position/local": _AVRVIOPositionLocalCallable,
    "avr/vio/velocity": _AVRVIOVelocityCallable,
    "avr/vio/attitude/euler/radians": _AVRVIOAttitudeEulerRadiansCallable,
    "avr/vio/attitude/quaternion": _AVRVIOAttitudeQuaternionCallable,
    "avr/vio/heading": _AVRVIOHeadingCallable,
    "avr/vio/confidence": _AVRVIOConfidenceCallable,
    "avr/vio/image/capture": _AVRVIOImageCaptureCallable,
    "avr/vio/image/request": _AVRVIOImageRequestCallable,
    "avr/vio/image/stream/enable": _AVRVIOImageStreamEnableCallable,
    "avr/vio/image/stream/disable": _AVREmptyMessageCallable,
    "avr/apriltags/vehicle_position": _AVRAprilTagsVehiclePositionCallable,
    "avr/apriltags/raw": _AVRAprilTagsRawCallable,
    "avr/apriltags/visible": _AVRAprilTagsVisibleCallable,
    "avr/apriltags/status": _AVRAprilTagsStatusCallable,
    "avr/status/led/pcm": _AVREmptyMessageCallable,
    "avr/status/led/vio": _AVREmptyMessageCallable,
    "avr/status/led/apriltags": _AVREmptyMessageCallable,
    "avr/status/led/fcm": _AVREmptyMessageCallable,
    "avr/status/led/thermal": _AVREmptyMessageCallable,
    "avr/thermal/reading": _AVRThermalReadingCallable,
    "avr/autonomous/enable": _AVREmptyMessageCallable,
    "avr/autonomous/disable": _AVREmptyMessageCallable,
    "avr/autonomous/building/enable": _AVRAutonomousBuildingEnableCallable,
    "avr/autonomous/building/disable": _AVRAutonomousBuildingDisableCallable,
}
"""
Complete dictionary of topics as keys, and function signatures that
accept the corresponding payload class as values.
This is used for `bell.avr.mqtt.module.MQTTModule.topic_callbacks`.
"""

_MQTTTopicPayloadTypedDict = TypedDict(
    "_MQTTTopicPayloadTypedDict",
    {
        "avr/pcm/color/set": AVRPCMColorSet,
        "avr/pcm/color/timed": AVRPCMColorTimed,
        "avr/pcm/laser/fire": AVREmptyMessage,
        "avr/pcm/laser/on": AVREmptyMessage,
        "avr/pcm/laser/off": AVREmptyMessage,
        "avr/pcm/servo/open": AVRPCMServo,
        "avr/pcm/servo/close": AVRPCMServo,
        "avr/pcm/servo/pwm/min": AVRPCMServoPWM,
        "avr/pcm/servo/pwm/max": AVRPCMServoPWM,
        "avr/pcm/servo/percent": AVRPCMServoPercent,
        "avr/pcm/servo/absolute": AVRPCMServoAbsolute,
        "avr/fcm/action/capture_home": AVREmptyMessage,
        "avr/fcm/action/sleep": AVRFCMActionSleep,
        "avr/fcm/action/arm": AVREmptyMessage,
        "avr/fcm/action/disarm": AVREmptyMessage,
        "avr/fcm/action/kill": AVREmptyMessage,
        "avr/fcm/action/land": AVREmptyMessage,
        "avr/fcm/action/takeoff": AVRFCMActionTakeoff,
        "avr/fcm/action/reboot": AVREmptyMessage,
        "avr/fcm/action/goto/global": AVRFCMGoToGlobal,
        "avr/fcm/action/goto/local": AVRFCMGoToLocal,
        "avr/fcm/action/mission/upload": AVRFCMMissionUpload,
        "avr/fcm/action/mission/start": AVREmptyMessage,
        "avr/fcm/hil_gps/stats": AVRFCMHILGPSStats,
        "avr/fcm/airborne": AVRFCMAirborne,
        "avr/fcm/landed": AVRFCMLanded,
        "avr/fcm/battery": AVRFCMBattery,
        "avr/fcm/armed": AVRFCMArmed,
        "avr/fcm/flight_mode": AVRFCMFlightMode,
        "avr/fcm/position/local": AVRFCMPositionLocal,
        "avr/fcm/position/global": AVRFCMPositionGlobal,
        "avr/fcm/position/home": AVRFCMPositionHome,
        "avr/fcm/attitude/euler/degrees": AVRFCMAttitudeEulerDegrees,
        "avr/fcm/velocity": AVRFCMVelocity,
        "avr/fcm/gps/info": AVRFCMGPSInfo,
        "avr/fusion/position/local": AVRFusionPositionLocal,
        "avr/fusion/velocity": AVRFusionVelocity,
        "avr/fusion/position/global": AVRFusionPositionGlobal,
        "avr/fusion/groundspeed": AVRFusionGroundspeed,
        "avr/fusion/course": AVRFusionCourse,
        "avr/fusion/heading": AVRFusionHeading,
        "avr/fusion/climb_rate": AVRFusionClimbRate,
        "avr/fusion/attitude/quaternion": AVRFusionAttitudeQuaternion,
        "avr/fusion/attitude/euler/radians": AVRFusionAttitudeEulerRadians,
        "avr/fusion/hil_gps/message": AVRFusionHILGPSMessage,
        "avr/vio/resync": AVRVIOResync,
        "avr/vio/position/local": AVRVIOPositionLocal,
        "avr/vio/velocity": AVRVIOVelocity,
        "avr/vio/attitude/euler/radians": AVRVIOAttitudeEulerRadians,
        "avr/vio/attitude/quaternion": AVRVIOAttitudeQuaternion,
        "avr/vio/heading": AVRVIOHeading,
        "avr/vio/confidence": AVRVIOConfidence,
        "avr/vio/image/capture": AVRVIOImageCapture,
        "avr/vio/image/request": AVRVIOImageRequest,
        "avr/vio/image/stream/enable": AVRVIOImageStreamEnable,
        "avr/vio/image/stream/disable": AVREmptyMessage,
        "avr/apriltags/vehicle_position": AVRAprilTagsVehiclePosition,
        "avr/apriltags/raw": AVRAprilTagsRaw,
        "avr/apriltags/visible": AVRAprilTagsVisible,
        "avr/apriltags/status": AVRAprilTagsStatus,
        "avr/status/led/pcm": AVREmptyMessage,
        "avr/status/led/vio": AVREmptyMessage,
        "avr/status/led/apriltags": AVREmptyMessage,
        "avr/status/led/fcm": AVREmptyMessage,
        "avr/status/led/thermal": AVREmptyMessage,
        "avr/thermal/reading": AVRThermalReading,
        "avr/autonomous/enable": AVREmptyMessage,
        "avr/autonomous/disable": AVREmptyMessage,
        "avr/autonomous/building/enable": AVRAutonomousBuildingEnable,
        "avr/autonomous/building/disable": AVRAutonomousBuildingDisable,
    },
    total=False
)
"""
TypedDict with topics as keys, and the associated payload class as values.
"""

_MQTTTopicPayloadTypeTypedDict = TypedDict(
    "_MQTTTopicPayloadTypeTypedDict",
    {
        "avr/pcm/color/set": Type[AVRPCMColorSet],
        "avr/pcm/color/timed": Type[AVRPCMColorTimed],
        "avr/pcm/laser/fire": Type[AVREmptyMessage],
        "avr/pcm/laser/on": Type[AVREmptyMessage],
        "avr/pcm/laser/off": Type[AVREmptyMessage],
        "avr/pcm/servo/open": Type[AVRPCMServo],
        "avr/pcm/servo/close": Type[AVRPCMServo],
        "avr/pcm/servo/pwm/min": Type[AVRPCMServoPWM],
        "avr/pcm/servo/pwm/max": Type[AVRPCMServoPWM],
        "avr/pcm/servo/percent": Type[AVRPCMServoPercent],
        "avr/pcm/servo/absolute": Type[AVRPCMServoAbsolute],
        "avr/fcm/action/capture_home": Type[AVREmptyMessage],
        "avr/fcm/action/sleep": Type[AVRFCMActionSleep],
        "avr/fcm/action/arm": Type[AVREmptyMessage],
        "avr/fcm/action/disarm": Type[AVREmptyMessage],
        "avr/fcm/action/kill": Type[AVREmptyMessage],
        "avr/fcm/action/land": Type[AVREmptyMessage],
        "avr/fcm/action/takeoff": Type[AVRFCMActionTakeoff],
        "avr/fcm/action/reboot": Type[AVREmptyMessage],
        "avr/fcm/action/goto/global": Type[AVRFCMGoToGlobal],
        "avr/fcm/action/goto/local": Type[AVRFCMGoToLocal],
        "avr/fcm/action/mission/upload": Type[AVRFCMMissionUpload],
        "avr/fcm/action/mission/start": Type[AVREmptyMessage],
        "avr/fcm/hil_gps/stats": Type[AVRFCMHILGPSStats],
        "avr/fcm/airborne": Type[AVRFCMAirborne],
        "avr/fcm/landed": Type[AVRFCMLanded],
        "avr/fcm/battery": Type[AVRFCMBattery],
        "avr/fcm/armed": Type[AVRFCMArmed],
        "avr/fcm/flight_mode": Type[AVRFCMFlightMode],
        "avr/fcm/position/local": Type[AVRFCMPositionLocal],
        "avr/fcm/position/global": Type[AVRFCMPositionGlobal],
        "avr/fcm/position/home": Type[AVRFCMPositionHome],
        "avr/fcm/attitude/euler/degrees": Type[AVRFCMAttitudeEulerDegrees],
        "avr/fcm/velocity": Type[AVRFCMVelocity],
        "avr/fcm/gps/info": Type[AVRFCMGPSInfo],
        "avr/fusion/position/local": Type[AVRFusionPositionLocal],
        "avr/fusion/velocity": Type[AVRFusionVelocity],
        "avr/fusion/position/global": Type[AVRFusionPositionGlobal],
        "avr/fusion/groundspeed": Type[AVRFusionGroundspeed],
        "avr/fusion/course": Type[AVRFusionCourse],
        "avr/fusion/heading": Type[AVRFusionHeading],
        "avr/fusion/climb_rate": Type[AVRFusionClimbRate],
        "avr/fusion/attitude/quaternion": Type[AVRFusionAttitudeQuaternion],
        "avr/fusion/attitude/euler/radians": Type[AVRFusionAttitudeEulerRadians],
        "avr/fusion/hil_gps/message": Type[AVRFusionHILGPSMessage],
        "avr/vio/resync": Type[AVRVIOResync],
        "avr/vio/position/local": Type[AVRVIOPositionLocal],
        "avr/vio/velocity": Type[AVRVIOVelocity],
        "avr/vio/attitude/euler/radians": Type[AVRVIOAttitudeEulerRadians],
        "avr/vio/attitude/quaternion": Type[AVRVIOAttitudeQuaternion],
        "avr/vio/heading": Type[AVRVIOHeading],
        "avr/vio/confidence": Type[AVRVIOConfidence],
        "avr/vio/image/capture": Type[AVRVIOImageCapture],
        "avr/vio/image/request": Type[AVRVIOImageRequest],
        "avr/vio/image/stream/enable": Type[AVRVIOImageStreamEnable],
        "avr/vio/image/stream/disable": Type[AVREmptyMessage],
        "avr/apriltags/vehicle_position": Type[AVRAprilTagsVehiclePosition],
        "avr/apriltags/raw": Type[AVRAprilTagsRaw],
        "avr/apriltags/visible": Type[AVRAprilTagsVisible],
        "avr/apriltags/status": Type[AVRAprilTagsStatus],
        "avr/status/led/pcm": Type[AVREmptyMessage],
        "avr/status/led/vio": Type[AVREmptyMessage],
        "avr/status/led/apriltags": Type[AVREmptyMessage],
        "avr/status/led/fcm": Type[AVREmptyMessage],
        "avr/status/led/thermal": Type[AVREmptyMessage],
        "avr/thermal/reading": Type[AVRThermalReading],
        "avr/autonomous/enable": Type[AVREmptyMessage],
        "avr/autonomous/disable": Type[AVREmptyMessage],
        "avr/autonomous/building/enable": Type[AVRAutonomousBuildingEnable],
        "avr/autonomous/building/disable": Type[AVRAutonomousBuildingDisable],
    },
    total=False
)
"""
TypedDict with topics as keys, and the associated payload class type as values.
"""

MQTTTopicPayload: _MQTTTopicPayloadTypeTypedDict = {
    "avr/pcm/color/set": AVRPCMColorSet,
    "avr/pcm/color/timed": AVRPCMColorTimed,
    "avr/pcm/laser/fire": AVREmptyMessage,
    "avr/pcm/laser/on": AVREmptyMessage,
    "avr/pcm/laser/off": AVREmptyMessage,
    "avr/pcm/servo/open": AVRPCMServo,
    "avr/pcm/servo/close": AVRPCMServo,
    "avr/pcm/servo/pwm/min": AVRPCMServoPWM,
    "avr/pcm/servo/pwm/max": AVRPCMServoPWM,
    "avr/pcm/servo/percent": AVRPCMServoPercent,
    "avr/pcm/servo/absolute": AVRPCMServoAbsolute,
    "avr/fcm/action/capture_home": AVREmptyMessage,
    "avr/fcm/action/sleep": AVRFCMActionSleep,
    "avr/fcm/action/arm": AVREmptyMessage,
    "avr/fcm/action/disarm": AVREmptyMessage,
    "avr/fcm/action/kill": AVREmptyMessage,
    "avr/fcm/action/land": AVREmptyMessage,
    "avr/fcm/action/takeoff": AVRFCMActionTakeoff,
    "avr/fcm/action/reboot": AVREmptyMessage,
    "avr/fcm/action/goto/global": AVRFCMGoToGlobal,
    "avr/fcm/action/goto/local": AVRFCMGoToLocal,
    "avr/fcm/action/mission/upload": AVRFCMMissionUpload,
    "avr/fcm/action/mission/start": AVREmptyMessage,
    "avr/fcm/hil_gps/stats": AVRFCMHILGPSStats,
    "avr/fcm/airborne": AVRFCMAirborne,
    "avr/fcm/landed": AVRFCMLanded,
    "avr/fcm/battery": AVRFCMBattery,
    "avr/fcm/armed": AVRFCMArmed,
    "avr/fcm/flight_mode": AVRFCMFlightMode,
    "avr/fcm/position/local": AVRFCMPositionLocal,
    "avr/fcm/position/global": AVRFCMPositionGlobal,
    "avr/fcm/position/home": AVRFCMPositionHome,
    "avr/fcm/attitude/euler/degrees": AVRFCMAttitudeEulerDegrees,
    "avr/fcm/velocity": AVRFCMVelocity,
    "avr/fcm/gps/info": AVRFCMGPSInfo,
    "avr/fusion/position/local": AVRFusionPositionLocal,
    "avr/fusion/velocity": AVRFusionVelocity,
    "avr/fusion/position/global": AVRFusionPositionGlobal,
    "avr/fusion/groundspeed": AVRFusionGroundspeed,
    "avr/fusion/course": AVRFusionCourse,
    "avr/fusion/heading": AVRFusionHeading,
    "avr/fusion/climb_rate": AVRFusionClimbRate,
    "avr/fusion/attitude/quaternion": AVRFusionAttitudeQuaternion,
    "avr/fusion/attitude/euler/radians": AVRFusionAttitudeEulerRadians,
    "avr/fusion/hil_gps/message": AVRFusionHILGPSMessage,
    "avr/vio/resync": AVRVIOResync,
    "avr/vio/position/local": AVRVIOPositionLocal,
    "avr/vio/velocity": AVRVIOVelocity,
    "avr/vio/attitude/euler/radians": AVRVIOAttitudeEulerRadians,
    "avr/vio/attitude/quaternion": AVRVIOAttitudeQuaternion,
    "avr/vio/heading": AVRVIOHeading,
    "avr/vio/confidence": AVRVIOConfidence,
    "avr/vio/image/capture": AVRVIOImageCapture,
    "avr/vio/image/request": AVRVIOImageRequest,
    "avr/vio/image/stream/enable": AVRVIOImageStreamEnable,
    "avr/vio/image/stream/disable": AVREmptyMessage,
    "avr/apriltags/vehicle_position": AVRAprilTagsVehiclePosition,
    "avr/apriltags/raw": AVRAprilTagsRaw,
    "avr/apriltags/visible": AVRAprilTagsVisible,
    "avr/apriltags/status": AVRAprilTagsStatus,
    "avr/status/led/pcm": AVREmptyMessage,
    "avr/status/led/vio": AVREmptyMessage,
    "avr/status/led/apriltags": AVREmptyMessage,
    "avr/status/led/fcm": AVREmptyMessage,
    "avr/status/led/thermal": AVREmptyMessage,
    "avr/thermal/reading": AVRThermalReading,
    "avr/autonomous/enable": AVREmptyMessage,
    "avr/autonomous/disable": AVREmptyMessage,
    "avr/autonomous/building/enable": AVRAutonomousBuildingEnable,
    "avr/autonomous/building/disable": AVRAutonomousBuildingDisable,
}
"""
Complete dictionary with topics as keys, and the associated payload class type
as values. This is used in `bell.avr.mqtt.serializer`.
"""