from builtins import Exception
from typing import Dict, List, Optional

class ParseError(Exception):
    def __init__(self, line_errors: Optional[Dict[int, str]] = ..., general_errors: Optional[List[str]] = ...) -> None: ...
    @property
    def line_errors(self) -> Optional[Dict[int, str]]: ...
    @property
    def general_errors(self) -> Optional[List[str]]: ...
    @property
    def message(self) -> str: ...
