class EmojiMeaning:
    def __init__(self):
        self.emoji_data=  {
    "😀": "Grinning Face",
    "😃": "Grinning Face with Big Eyes",
    "😄": "Grinning Face with Smiling Eyes",
    "😁": "Beaming Face with Smiling Eyes",
    "😆": "Grinning Squinting Face",
    "😅": "Grinning Face with Sweat",
    "😂": "Face with Tears of Joy",
    "🤣": "Rolling on the Floor Laughing",
    "😭": "Loudly Crying Face",
    "😉": "Winking Face",
    "😗": "Kissing Face",
    "😙": "Kissing Face with Smiling Eyes",
    "😚": "Kissing Face with Closed Eyes",
    "😘": "Face Blowing a Kiss",
    "🥰": "Smiling Face with Hearts",
    "😍": "Heart Eyes",
    "🤩": "Star-Struck",
    "🥳": "Partying Face",
    "🫠": "Foggy",
    "🙃": "Upside-Down Face",
    "🙂": "Slightly Smiling Face",
    "🥲": "Smiling Face with Tear",
    "🥹": "Face with Spiral Eyes",
    "😊": "Smiling Face with Smiling Eyes",
    "☺": "Smiling Face",
    "😌": "Relieved Face",
    "😏": "Smirking Face",
    "😴": "Sleeping Face",
    "😪": "Sleepy Face",
    "🤤": "Drooling Face",
    "😋": "Savoring Food",
    "😛": "Face with Tongue Out",
    "😝": "Squinting Face with Tongue Out",
    "😜": "Winking Face with Tongue Out",
    "🤪": "Zany Face",
    "🥴": "Woozy Face",
    "😔": "Pensive Face",
    "🥺": "Pleading Face",
    "😬": "Grimacing Face",
    "🫥": "Rocking in Chair",
    "😑": "Expressionless Face",
    "😐": "Neutral Face",
    "😶": "Face Without Mouth",
    "😶‍🌫": "Face in Clouds",
    "🤐": "Zipper-Mouth Face",
    "🫡": "Potted Plant",
    "🤔": "Thinking Face",
    "🤫": "Shushing Face",
    "🫢": "Bubble Tea",
    "🤭": "Face with Hand Over Mouth",
    "🥱": "Yawning Face",
    "🤗": "Hugging Face",
    "🫣": "Nest with Eggs",
    "😱": "Face Screaming in Fear",
    "🤨": "Face with Raised Eyebrow",
    "🧐": "Face with Monocle",
    "😒": "Unamused Face",
    "🙄": "Face with Rolling Eyes",
    "😮‍💨": "Face Exhaling",
    "😤": "Face with Steam from Nose",
    "😠": "Angry Face",
    "😡": "Pouting Face",
    "🤬": "Face with Symbols on Mouth",
    "😞": "Disappointed Face",
    "😓": "Downcast Face with Sweat",
    "😟": "Worried Face",
    "😥": "Sad but Relieved Face",
    "😢": "Crying Face",
    "☹": "Frowning Face",
    "🙁": "Slightly Frowning Face",
    "🫤": "Lungs",
    "😕": "Confused Face",
    "😰": "Anxious Face with Sweat",
    "😨": "Fearful Face",
    "😧": "Face with Open Mouth",
    "😦": "Frowning Face with Open Mouth",
    "😮": "Face with Open Mouth",
    "😯": "Surprised Face",
    "😲": "Astonished Face",
    "😳": "Flushed Face",
    "🤯": "Exploding Head",
    "😖": "Confounded Face",
    "😣": "Persevering Face",
    "😩": "Weary Face",
    "😫": "Tired Face",
    "😵": "Face with Spiral Eyes",
    "😵‍💫": "Face with Spiral Eyes and Star",
    "🫨": "Garlic",
    "🥶": "Cold Face",
    "🥵": "Hot Face",
    "🤢": "Nauseated Face",
    "🤮": "Face Vomiting",
    "🤧": "Sneezing Face",
    "🤒": "Sick Face",
    "🤕": "Face with Head-Bandage",
    "😷": "Face with Medical Mask",
    "🤥": "Lying Face",
    "😇": "Smiling Face with Halo",
    "🤠": "Cowboy Hat Face",
    "🤑": "Money-Mouth Face",
    "🤓": "Nerd Face",
    "😎": "Smiling Face with Sunglasses",
    "🥸": "Disguised Face",
    "🤡": "Clown Face",
    "😈": "Smiling Face with Horns",
    "👿": "Imp",
    "👻": "Ghost",
    "🎃": "Jack-O-Lantern",
    "💩": "Pile of Poo",
    "🤖": "Robot Face",
    "👽": "Alien",
    "👾": "Alien Monster",
    "🌛": "First Quarter Moon Face",
    "🌜": "Last Quarter Moon Face",
    "🌚": "New Moon Face",
    "🌝": "Full Moon Face",
    "🌞": "Sun with Face",
    "☠": "Skull and Crossbones",
    "👹": "Japanese Ogre",
    "👺": "Japanese Goblin",
    "🔥": "Fire",
    "💯": "Hundred Points",
    "💫": "Dizzy",
    "⭐": "Star",
    "🌟": "Glowing Star",
    "✨": "Sparkles",
    "💥": "Collision",
    "💨": "Dashing Away",
    "💦": "Sweat Droplets",
    "💤": "Zzz",
    "🕳": "Hole",
    "🎉": "Party Popper",
    "🙈": "See-No-Evil Monkey",
    "🙉": "Hear-No-Evil Monkey",
    "🙊": "Speak-No-Evil Monkey",
    "😺": "Grinning Cat Face",
    "😸": "Grinning Cat Face with Smiling Eyes",
    "😹": "Cat Face with Tears of Joy",
    "😻": "Smiling Cat Face with Heart-Eyes",
    "😼": "Cat Face with Wry Smile",
    "😽": "Kissing Cat Face",
    "🙀": "Weary Cat Face",
    "😿": "Crying Cat Face",
    "😾": "Pouting Cat Face",
    "❤": "Red Heart",
    "🧡": "Orange Heart",
    "💛": "Yellow Heart",
    "💚": "Green Heart",
    "🩵": "Sari",
    "💙": "Blue Heart",
    "💜": "Purple Heart",
    "🤎": "Brown Heart",
    "🖤": "Black Heart",
    "🩶": "Ballet Shoes",
    "🤍": "White Heart",
    "🩷": "Briefs",
    "💘": "Heart with Arrow",
    "💝": "Heart with Ribbon",
    "💖": "Sparkling Heart",
    "💗": "Growing Heart",
    "💓": "Beating Heart",
    "💞": "Revolving Hearts",
    "💕": "Two Hearts",
    "💌": "Love Letter",
    "💟": "Heart Decoration",
    "♥": "Heart Suit",
    "❣": "Heavy Heart Exclamation",
    "❤‍🩹": "Mending Heart",
    "💔": "Broken Heart",
    "❤‍🔥": "Heart on Fire",
    "💋": "Kiss Mark",
    "🫂": "Hugging Face",
    "👥": "People Holding Hands",
    "👤": "Bust in Silhouette",
    "🗣": "Speaking Head",
    "👣": "Footprints",
    "🧠": "Brain",
    "🫀": "Anatomical Heart",
    "🫁": "Lungs",
    "🩸": "Drop of Blood",
    "🦠": "Microbe",
    "🦷": "Tooth",
    "🦴": "Bone",
    "💀": "Skull",
    "👀": "Eyes",
    "👁": "Eye",
    "👄": "Mouth",
    "🫦": "Toothbrush",
    "👅": "Tongue",
    "👃": "Nose",
    "👂": "Ear",
    "🦻": "Ear with Hearing Aid",
    "🦶": "Footprints",
    "🦶🦶": "Feet",
    "🦵": "Leg",
    "🦿": "Mechanical Leg",
    "🦾": "Mechanical Arm",
    "💪": "Flexed Biceps",
    "👏": "Clapping Hands",
    "👍": "Thumbs Up",
    "👎": "Thumbs Down",
    "🫶": "Pinched Fingers",
    "🙌": "Raising Hands",
    "👐": "Open Hands",
    "🤲": "Palms Up Together",
    "🤝": "Handshake",
    "🤜": "Right-Facing Fist",
    "🤛": "Left-Facing Fist",
    "✊": "Raised Fist",
    "👊": "Oncoming Fist",
    "🫳": "Raised Hand with Fingers Splayed",
    "🫴": "Hand with Index and Middle Fingers Crossed",
    "🫱": "Hand with Part Between Middle and Ring Fingers",
    "🫲": "I Love You Hand Sign",
    "🫸": "Sign of the Horns",
    "🫷": "Call Me Hand Sign",
    "👋": "Waving Hand",
    "🤚": "Raised Back of Hand",
    "🖐": "Hand with Fingers Splayed",
    "✋": "Raised Hand",
    "🖖": "Vulcan Salute",
    "🤟": "Love-You Gesture",
    "🤘": "Sign of the Horns",
    "✌": "Victory Hand",
    "🤞": "Crossed Fingers",
    "🫰": "Bubble Wrap",
    "🤙": "Call Me Hand",
    "🤌": "Pinch Gesture",
    "🤏": "Pinching Hand",
    "👌": "OK Hand",
    "🫵": "Pinched Fingers",
    "👉": "Backhand Index Pointing Right",
    "👈": "Backhand Index Pointing Left",
    "☝": "Index Pointing Up",
    "👆": "Backhand Index Pointing Up",
    "👇": "Backhand Index Pointing Down",
    "🖕": "Middle Finger",
    "✍": "Writing Hand",
    "🤳": "Selfie",
    "🙏": "Folded Hands",
    "💅": "Nail Polish",
    "🙇": "Person Bowing Deeply",
    "🙋": "Person Raising Hand",
    "💁": "Person Tipping Hand",
    "🙆": "Person Gesturing OK",
    "🙅": "Person Gesturing No",
    "🤷": "Person Shrugging",
    "🤦": "Person Facepalming",
    "🙍": "Person Pouting",
    "🙎": "Person Frowning",
    "🧏": "Deaf Person",
    "💆": "Person Getting Massage",
    "💇": "Person Getting Haircut",
    "🧖": "Person in Steamy Room",
    "🛀": "Person Taking Bath",
    "🛌": "Person in Bed",
    "🧘": "Person in Lotus Position",
    "🧑‍🦯": "Person with White Cane",
    "🧑‍🦼": "Person in Motorized Wheelchair",
    "🧎": "Person Kneeling",
    "🧎": "Person Kneeling (Alternative)",
    "🧍": "Person Standing",
    "🚶": "Person Walking",
    "🏃": "Person Running",
    "🤸": "Person Cartwheeling",
    "🏋️": "Person Lifting Weights",
    "⛹️": "Person Bouncing Ball",
    "🤾": "Person Playing Handball",
    "🚴": "Person Biking",
    "🚵": "Person Mountain Biking",
    "🧗": "Person Climbing",
    "🤼": "People Wrestling",
    "🤹": "Person Juggling",
    "🏌️": "Person Golfing",
    "🏇": "Person Horse Racing",
    "🤺": "Person Fencing",
    "⛷️": "Skier",
    "🏂": "Snowboarder",
    "🪂": "Person Parachuting",
    "🪂": "Person Parachuting (Alternative)",
    "🚣": "Person Rowing Boat",
    "🚣": "Person Rowing Boat (Alternative)",
    "🏊": "Person Swimming",
    "🤽": "Person Playing Water Polo",
    "🧜": "Merperson",
    "🧚": "Fairy",
    "🧞": "Genie",
    "🧝": "Elf",
    "🧙": "Mage",
    "🧛": "Vampire",
    "🧟": "Zombie",
    "🦹": "Supervillain",
    "🦸": "Superhero",
    "🥷": "Ninja",
    "🧑‍🎄": "Mx Claus",
    "👼": "Baby Angel",
    "💂": "Guard",
    "👸": "Princess",
    "🤵": "Man in Tuxedo",
    "👰": "Bride with Veil",
    "🧑‍🚀": "Astronaut",
    "👷": "Construction Worker",
    "👮": "Police Officer",
    "🕵️": "Detective",
    "🧑‍✈️": "Pilot",
    "🧑‍🔬": "Scientist",
    "🧑‍⚕️": "Health Worker",
    "🧑‍🔧": "Mechanic",
    "🧑‍🏭": "Factory Worker",
    "🧑‍🚒": "Firefighter",
    "🧑‍🌾": "Farmer",
    "🧑‍🏫": "Teacher",
    "🧑‍🎓": "Student",
    "🧑‍💼": "Office Worker",
    "🧑‍⚖️": "Judge",
    "🧑‍💻": "Technologist",
    "🧑‍🎤": "Singer",
    "🧑‍🎨": "Artist",
    "🧑‍🍳": "Cook",
    "👳": "Person Wearing Turban",
    "🧕": "Woman with Headscarf",
    "👲": "Person with Skullcap",
    "👶": "Baby",
    "🧒": "Child",
    "🧑": "Adult",
    "🧓": "Older Adult",
    "🧑‍🦳": "Person with White Hair",
    "🧑‍🦰": "Person with Red Hair",
    "👱": "Person with Blond Hair",
    "🧑‍🦱": "Person with Curly Hair",
    "🧑‍🦲": "Person with Bald Head",
    "🧔": "Bearded Person",
    "🕴️": "Man in Suit Levitating",
    "💃": "Woman Dancing",
    "🕺": "Man Dancing",
    "👯": "People with Bunny Ears",
    "🧑‍🤝‍🧑": "People Holding Hands",
    "👭": "Women Holding Hands",
    "👬": "Men Holding Hands",
    "👫": "Man and Woman Holding Hands",
    "💏": "Kiss",
    "👩‍❤️‍💋‍👨": "Kiss: Woman",
    "👨‍❤️‍💋‍👨": "Kiss: Man",
    "👩‍❤️‍💋‍👩": "Kiss: Woman",
    "💑": "Couple with Heart",
    "👩‍❤️‍👨": "Couple with Heart: Woman",
    "👨‍❤️‍👨": "Couple with Heart: Man",
    "👩‍❤️‍👩": "Couple with Heart: Woman",
    "🤰": "Pregnant Woman",
    "🤱": "Breastfeeding",
    "🧑‍🍼": "Person Feeding Baby",
    "👪": "Family",
    "💐": "Bouquet",
    "🌹": "Rose",
    "🥀": "Wilted Flower",
    "🌺": "Hibiscus",
    "🌷": "Tulip",
    "🌸": "Cherry Blossom",
    "💮": "White Flower",
    "🏵️": "Rosette",
    "🌻": "Sunflower",
    "🌼": "Blossom",
    "🍂": "Fallen Leaf",
    "🍁": "Maple Leaf",
    "🍄": "Mushroom",
    "🌾": "Sheaf of Rice",
    "🌱": "Seedling",
    "🌿": "Herb",
    "🍃": "Leaf Fluttering in Wind",
    "☘️": "Shamrock",
    "🍀": "Four Leaf Clover",
    "🪴": "Potted Plant",
    "🌵": "Cactus",
    "🌴": "Palm Tree",
    "🌳": "Deciduous Tree",
    "🌲": "Pine Tree",
    "🪵": "Wood",
    "🪨": "Rock",
    "⛰️": "Mountain",
    "🏔️": "Snow-Capped Mountain",
    "❄️": "Snowflake",
    "☃️": "Snowman",
    "⛄": "Snowman Without Snow",
    "🌫️": "Foggy",
    "🌡️": "Thermometer",
    "🌋": "Volcano",
    "🏜️": "Desert",
    "🏞️": "National Park",
    "🏝️": "Desert Island",
    "🏖️": "Beach with Umbrella",
    "🌅": "Sunrise",
    "🌄": "Sunrise Over Mountains",
    "🌈": "Rainbow",
    "🌊": "Water Wave",
    "🌬️": "Wind Face",
    "🌀": "Cyclone",
    "🌪️": "Tornado",
    "⚡": "High Voltage",
    "☔": "Umbrella with Rain Drops",
    "💧": "Droplet",
    "🌧️": "Cloud with Rain",
    "🌩️": "Cloud with Lightning",
    "⛈️": "Cloud with Lightning and Rain",
    "🌨️": "Cloud with Snow",
    "☁️": "Cloud",
    "🌦️": "Sun Behind Rain Cloud",
    "🌥️": "Sun Behind Large Cloud",
    "⛅": "Sun Behind Cloud",
    "🌤️": "Sun Behind Small Cloud",
    "☀️": "Sun",
    "🌝": "Full Moon with Face",
    "🌜": "First Quarter Moon",
    "🌛": "Last Quarter Moon",
    "🌙": "Crescent Moon",
    "☄️": "Comet",
    "🕳️": "Hole",
    "🌠": "Shooting Star",
    "🌌": "Milky Way",
    "🌍": "Earth Globe Europe-Africa",
    "🌎": "Earth Globe Americas",
    "🌏": "Earth Globe Asia-Australia",
    "🪐": "Ringed Planet",
    "🌑": "New Moon",
    "🌒": "Waxing Crescent Moon",
    "🌓": "First Quarter Moon",
    "🌔": "Waxing Gibbous Moon",
    "🌕": "Full Moon",
    "🌖": "Waning Gibbous Moon",
    "🌗": "Last Quarter Moon",
    "🌘": "Waning Crescent Moon",
    "🐵": "Monkey Face",
    "🦁": "Lion Face",
    "🐯": "Tiger Face",
    "🐱": "Cat Face",
    "🐶": "Dog Face",
    "🐺": "Wolf Face",
    "🐻": "Bear Face",
    "🐻‍❄️": "Polar Bear Face",
    "🐨": "Koala Face",
    "🐼": "Panda Face",
    "🐹": "Hamster Face",
    "🐭": "Mouse Face",
    "🐰": "Rabbit Face",
    "🦊": "Fox Face",
    "🦝": "Raccoon",
    "🐮": "Cow Face",
    "🐷": "Pig Face",
    "🐽": "Pig Nose",
    "🐗": "Boar",
    "🦓": "Zebra",
    "🦄": "Unicorn Face",
    "🐴": "Horse Face",
    "🐲": "Dragon Face",
    "🦎": "Lizard",
    "🐉": "Dragon",
    "🦖": "T-Rex",
    "🦕": "Sauropod",
    "🐢": "Turtle",
    "🐊": "Crocodile",
    "🐍": "Snake",
    "🐸": "Frog Face",
    "🐇": "Rabbit",
    "🐁": "Mouse",
    "🐀": "Rat",
    "🐈": "Cat",
    "🐈‍⬛": "Black Cat",
    "🐩": "Poodle",
    "🐕": "Dog",
    "🦮": "Guide Dog",
    "🐕‍🦺": "Service Dog",
    "🐖": "Pig Nose",
    "🐎": "Horse",
    "🐄": "Cow",
    "🐂": "Ox",
    "🐃": "Water Buffalo",
    "🦬": "Bison",
    "🐑": "Ewe",
    "🐐": "Goat",
    "🦌": "Deer",
    "🦙": "Llama",
    "🦥": "Sloth",
    "🦘": "Kangaroo",
    "🐘": "Elephant",
    "🦣": "Mammoth",
    "🦏": "Rhinoceros",
    "🦛": "Hippopotamus",
    "🦒": "Giraffe Face",
    "🐆": "Leopard",
    "🐅": "Tiger",
    "🐒": "Monkey",
    "🦍": "Gorilla",
    "🦧": "Orangutan",
    "🐪": "Camel",
    "🐫": "Two-Hump Camel",
    "🐿️": "Chipmunk",
    "🦫": "Beaver",
    "🦨": "Skunk",
    "🦡": "Badger",
    "🦔": "Hedgehog",
    "🦇": "Bat",
    "🪶": "Feather",
    "🐦": "Bird",
    "🐓": "Rooster",
    "🐔": "Chicken",
    "🐣": "Hatching Chick",
    "🐤": "Baby Chick",
    "🐥": "Front-Facing Baby Chick",
    "🦅": "Eagle",
    "🦉": "Owl",
    "🦜": "Parrot",
    "🕊️": "Dove",
    "🦤": "Dodo",
    "🦢": "Swan",
    "🦆": "Duck",
    "🦩": "Flamingo",
    "🦚": "Peacock",
    "🦃": "Turkey",
    "🐧": "Penguin",
    "🦭": "Seal",
    "🦈": "Shark",
    "🐬": "Dolphin",
    "🐋": "Whale",
    "🐳": "Spouting Whale",
    "🐟": "Fish",
    "🐠": "Tropical Fish",
    "🐡": "Blowfish",
    "🦐": "Shrimp",
    "🦞": "Lobster",
    "🦀": "Crab",
    "🦑": "Squid",
    "🐙": "Octopus",
    "🦪": "Oyster",
    "🦂": "Beetle",
    "🕷️": "Spider",
    "🕸️": "Spider Web",
    "🐚": "Spiral Shell",
    "🐌": "Snail",
    "🐜": "Ant",
    "🦗": "Cricket",
    "🪲": "Cockroach",
    "🦟": "Mosquito",
    "🪳": "Fly",
    "🪰": "Fly (Alternative)",
    "🐝": "Honeybee",
    "🐞": "Lady Beetle",
    "🦋": "Butterfly",
    "🐛": "Bug",
    "🪱": "Worm",
    "🐾": "Paw Prints",
    "🍓": "Strawberry",
    "🍒": "Cherries",
    "🍎": "Red Apple",
    "🍉": "Watermelon",
    "🍑": "Peach",
    "🍊": "Tangerine",
    "🥭": "Mango",
    "🍍": "Pineapple",
    "🍌": "Banana",
    "🍋": "Lemon",
    "🍈": "Melon",
    "🍏": "Green Apple",
    "🍐": "Pear",
    "🥝": "Kiwi Fruit",
    "🫒": "Olive",
    "🫐": "Blueberries",
    "🍇": "Grapes",
    "🥥": "Coconut",
    "🍅": "Tomato",
    "🌶️": "Hot Pepper",
    "🥕": "Carrot",
    "🍠": "Roasted Sweet Potato",
    "🧅": "Onion",
    "🌽": "Ear of Corn",
    "🥦": "Broccoli",
    "🥒": "Cucumber",
    "🥬": "Leafy Green",
    "🫑": "Bell Pepper",
    "🥑": "Avocado",
    "🍆": "Eggplant",
    "🧄": "Garlic",
    "🥔": "Potato",
    "🌰": "Chestnut",
    "🥜": "Peanuts",
    "🍞": "Bread",
    "🫓": "Flatbread",
    "🥐": "Croissant",
    "🥖": "Baguette Bread",
    "🥯": "Bagel",
    "🧇": "Waffle",
    "🥞": "Pancakes",
    "🍳": "Cooking",
    "🥚": "Egg",
    "🧀": "Cheese Wedge",
    "🥓": "Bacon",
    "🥩": "Cut of Meat",
    "🍖": "Meat on Bone",
    "🍔": "Hamburger",
    "🌭": "Hot Dog",
    "🥪": "Sandwich",
    "🥨": "Pretzel",
    "🍟": "French Fries",
    "🍕": "Pizza",
    "🫔": "Tamale",
    "🌮": "Taco",
    "🌯": "Burrito",
    "🥙": "Stuffed Flatbread",
    "🧆": "Falafel",
    "🥘": "Shallow Pan of Food",
    "🍝": "Spaghetti",
    "🥫": "Canned Food",
    "🫕": "Fondue",
    "🥣": "Bowl with Spoon",
    "🥗": "Green Salad",
    "🍲": "Pot of Food",
    "🍛": "Curry Rice",
    "🍜": "Steaming Bowl",
    "🦞": "Lobster (Alternative)",
    "🍣": "Sushi",
    "🍤": "Fried Shrimp",
    "🥡": "Takeout Box",
    "🍚": "Cooked Rice",
    "🍱": "Bento Box",
    "🥟": "Dumpling",
    "🍢": "Oden",
    "🍙": "Rice Ball",
    "🍘": "Rice Cracker",
    "🍥": "Fish Cake with Swirl",
    "🍡": "Dango",
    "🥠": "Fortune Cookie",
    "🥮": "Moon Cake",
    "🍧": "Shaved Ice",
    "🍨": "Ice Cream",
    "🍦": "Soft Ice Cream",
    "🥧": "Pie",
    "🍰": "Shortcake",
    "🍮": "Custard",
    "🎂": "Birthday Cake",
    "🧁": "Cupcake",
    "🍭": "Lollipop",
    "🍬": "Candy",
    "🍫": "Chocolate Bar",
    "🍩": "Doughnut",
    "🍪": "Cookie",
    "🍯": "Honey Pot",
    "🧂": "Salt",
    "🧈": "Butter",
    "🍿": "Popcorn",
    "🧊": "Ice",
    "🥤": "Cup with Straw",
    "🧋": "Bubble Tea",
    "🧃": "Beverage Box",
    "🥛": "Glass of Milk",
    "🍼": "Baby Bottle",
    "🍵": "Teacup Without Handle",
    "☕": "Hot Beverage",
    "🫖": "Teapot",
    "🧉": "Mate",
    "🍺": "Beer Mug",
    "🍻": "Clinking Beer Mugs",
    "🥂": "Clinking Glasses",
    "🍾": "Bottle with Popping Cork",
    "🍷": "Wine Glass",
    "🥃": "Tumbler Glass",
    "🍸": "Cocktail Glass",
    "🍹": "Tropical Drink",
    "🍶": "Sake",
    "🥢": "Chopsticks",
    "🍴": "Fork and Knife",
    "🥄": "Spoon",
    "🔪": "Kitchen Knife",
    "🍽️": "Fork and Knife with Plate",
    "🛑": "Stop Sign",
    "🚧": "Construction Sign",
    "🚨": "Police Car Light",
    "⛽": "Fuel Pump",
    "🛢️": "Oil Drum",
    "🧭": "Compass",
    "⚓": "Anchor",
    "🚏": "Bus Stop",
    "🚇": "Metro",
    "🚥": "Horizontal Traffic Light",
    "🚦": "Vertical Traffic Light",
    "🛴": "Kick Scooter",
    "🦽": "Manual Wheelchair",
    "🦼": "Motorized Wheelchair",
    "🚲": "Bicycle",
    "🛵": "Motor Scooter",
    "🏍️": "Motorcycle",
    "🚙": "Sport Utility Vehicle",
    "🚗": "Automobile",
    "🛻": "Pickup Truck",
    "🚐": "Minibus",
    "🚚": "Delivery Truck",
    "🚛": "Articulated Lorry",
    "🚜": "Tractor",
    "🏎️": "Racing Car",
    "🚒": "Fire Engine",
    "🚑": "Ambulance",
    "🚓": "Police Car",
    "🚕": "Taxi",
    "🛺": "Auto Rickshaw",
    "🚌": "Bus",
    "🚈": "Light Rail",
    "🚝": "Monorail",
    "🚅": "High-Speed Train",
    "🚄": "Bullet Train",
    "🚂": "Steam Locomotive",
    "🚃": "Railway Car",
    "🚋": "Tram Car",
    "🚎": "Trolleybus",
    "🚞": "Mountain Railway",
    "🚊": "Tram",
    "🚉": "Station",
    "🚍": "Oncoming Bus",
    "🚔": "Oncoming Police Car",
    "🚘": "Oncoming Automobile",
    "🚖": "Oncoming Taxi",
    "🚆": "Oncoming Train",
    "🚢": "Ship",
    "🛳️": "Passenger Ship",
    "🛥️": "Motor Boat",
    "🚤": "Speedboat",
    "⛴️": "Ferry",
    "⛵": "Sailboat",
    "🛶": "Canoe",
    "🚟": "Suspension Railway",
    "🚠": "Mountain Cableway",
    "🚡": "Aerial Tramway",
    "🚁": "Helicopter",
    "🛸": "Flying Saucer",
    "🚀": "Rocket",
    "✈️": "Airplane",
    "🛫": "Airplane Departure",
    "🛬": "Airplane Arrival",
    "🛩️": "Small Airplane",
    "🎢": "Roller Coaster",
    "🎡": "Ferris Wheel",
    "🎠": "Carousel Horse",
    "🎪": "Circus Tent",
    "🗼": "Tokyo Tower",
    "🗽": "Statue of Liberty",
    "🗿": "Moyai",
    "🗻": "Mount Fuji",
    "🏛️": "Classical Building",
    "💈": "Barber Pole",
    "⛲": "Fountain",
    "⛩️": "Shinto Shrine",
    "🕍": "Synagogue",
    "🕌": "Mosque",
    "🕋": "Kaaba",
    "🛕": "Hindu Temple",
    "⛪": "Church",
    "💒": "Wedding",
    "🏩": "Love Hotel",
    "🏯": "Japanese Castle",
    "🏰": "Castle",
    "🏗️": "Building Construction",
    "🏢": "Office Building",
    "🏭": "Factory",
    "🏬": "Department Store",
    "🏪": "Convenience Store",
    "🏟️": "Stadium",
    "🏦": "Bank",
    "🏫": "School",
    "🏨": "Hotel",
    "🏣": "Japanese Post Office",
    "🏤": "Post Office",
    "🏥": "Hospital",
    "🏚️": "Derelict House",
    "🏠": "House",
    "🏡": "House with Garden",
    "🏘️": "Houses",
    "🛖": "Hut",
    "⛺": "Tent",
    "🏕️": "Camping",
    "⛱️": "Umbrella on Ground",
    "🏙️": "Cityscape",
    "🌆": "Cityscape at Dusk",
    "🌇": "Sunset",
    "🌃": "Night with Stars",
    "🌉": "Bridge at Night",
    "🌁": "Foggy",
    "🛤️": "Railway Track",
    "🛣️": "Motorway",
    "🗾": "Map of Japan",
    "🗺️": "World Map",
    "🌐": "Globe with Meridians",
    "💺": "Seat",
    "🧳": "Luggage",
    "🎊": "Confetti Ball",
    "🎈": "Balloon",
    "🎀": "Ribbon",
    "🎁": "Wrapped Gift",
    "🎇": "Sparkler",
    "🎆": "Fireworks",
    "🧨": "Firecracker",
    "🧧": "Red Envelope",
    "🪔": "Diya Lamp",
    "🪅": "Wind Chime",
    "🎐": "Wind Chime",
    "🎏": "Carp Streamer",
    "🎎": "Japanese Dolls",
    "🎑": "Moon Viewing Ceremony",
    "🎍": "Pine Decoration",
    "🎋": "Tanabata Tree",
    "🎄": "Christmas Tree",
    "🎗️": "Reminder Ribbon",
    "🥇": "1st Place Medal",
    "🥈": "2nd Place Medal",
    "🥉": "3rd Place Medal",
    "🏅": "Sports Medal",
    "🎖️": "Military Medal",
    "🏆": "Trophy",
    "📢": "Loudspeaker",
    "⚽": "Soccer Ball",
    "⚾": "Baseball",
    "🥎": "Softball",
    "🏀": "Basketball",
    "🏐": "Volleyball",
    "🏈": "American Football",
    "🏉": "Rugby Football",
    "🥅": "Goal Net",
    "🎾": "Tennis",
    "🏸": "Badminton",
    "🥍": "Lacrosse",
    "🏏": "Cricket Game",
    "🏑": "Field Hockey",
    "🏒": "Ice Hockey",
    "🥌": "Curling Stone",
    "🛷": "Sled",
    "🎿": "Skis",
    "⛸️": "Ice Skate",
    "🛼": "Roller Skate",
    "🩰": "Ballet Shoes",
    "🛹": "Skateboard",
    "⛳": "Flag in Hole",
    "🎯": "Direct Hit",
    "🏹": "Bow and Arrow",
    "🥏": "Flying Disc",
    "🪃": "Boomerang",
    "🪁": "Kite",
    "🎣": "Fishing Pole",
    "🤿": "Diving Mask",
    "🩱": "One-Piece Swimsuit",
    "🎽": "Running Shirt",
    "🥋": "Martial Arts Uniform",
    "🥊": "Boxing Glove",
    "🎱": "Pool 8 Ball",
    "🏓": "Ping Pong",
    "🎳": "Bowling",
    "♟️": "Chess Pawn",
    "🪀": "Yo-Yo",
    "🧩": "Jigsaw Puzzle Piece",
    "🎮": "Video Game",
    "🕹️": "Joystick",
    "🔫": "Pistol",
    "🎲": "Game Die",
    "🎰": "Slot Machine",
    "🎴": "Flower Playing Cards",
    "🀄": "Mahjong Tile Red Dragon",
    "🃏": "Playing Card Black Joker",
    "🪄": "Magic Wand",
    "🎩": "Top Hat",
    "📷": "Camera",
    "📸": "Camera with Flash",
    "🖼️": "Framed Picture",
    "🎨": "Artist Palette",
    "🖌️": "Paintbrush",
    "🖍️": "Crayon",
    "🪡": "Sewing Needle",
    "🧵": "Thread",
    "🧶": "Yarn",
    "🎹": "Musical Keyboard",
    "🎷": "Saxophone",
    "🎺": "Trumpet",
    "🎸": "Guitar",
    "🪕": "Banjo",
    "🎻": "Violin",
    "🪘": "Accordion",
    "🥁": "Drum",
    "🪗": "Long Drum",
    "🎤": "Microphone",
    "🎧": "Headphone",
    "🎚️": "Studio Microphone",
    "🎛️": "Control Knobs",
    "🎙️": "Studio Microphone",
    "📻": "Radio",
    "📺": "Television",
    "📼": "Videocassette",
    "📹": "Video Camera",
    "📽️": "Film Projector",
    "🎥": "Movie Camera",
    "🎞️": "Film Frames",
    "🎬": "Clapper Board",
    "🎭": "Performing Arts",
    "🎫": "Ticket",
    "🎟️": "Admission Tickets",
    "📱": "Mobile Phone",
    "☎️": "Telephone",
    "📞": "Telephone Receiver",
    "📟": "Pager",
    "📠": "Fax Machine",
    "🔌": "Electric Plug",
    "🔋": "Battery",
    "🖲️": "Trackball",
    "💽": "Computer Disk",
    "💾": "Floppy Disk",
    "💿": "Optical Disk",
    "📀": "DVD",
    "🖥️": "Desktop Computer",
    "💻": "Laptop Computer",
    "⌨️": "Keyboard",
    "🖨️": "Desktop Printer",
    "🖱️": "Computer Mouse",
    "🪙": "Loudspeaker",
    "💸": "Money with Wings",
    "💵": "Dollar Banknote",
    "💴": "Yen Banknote",
    "💶": "Euro Banknote",
    "💷": "Pound Banknote",
    "💳": "Credit Card",
    "💰": "Money Bag",
    "🧾": "Receipt",
    "🧮": "Abacus",
    "⚖️": "Balance Scale",
    "🛒": "Shopping Cart",
    "🛍️": "Shopping Bags",
    "🕯️": "Candle",
    "💡": "Light Bulb",
    "🔦": "Flashlight",
    "🏮": "Red Paper Lantern",
    "🧱": "Brick",
    "🪟": "Window",
    "🪞": "Mirror",
    "🚪": "Door",
    "🪑": "Chair",
    "🛏️": "Bed",
    "🛋️": "Couch and Lamp",
    "🚿": "Shower",
    "🛁": "Bathtub",
    "🚽": "Toilet",
    "🧻": "Roll of Toilet Paper",
    "🪠": "Plunger",
    "🧸": "Teddy Bear",
    "🪆": "Pinata",
    "🧷": "Safety Pin",
    "🪢": "Threaded Needle",
    "🧹": "Broom",
    "🧽": "Sponge",
    "🧴": "Lotion Bottle",
    "🧼": "Soap",
    "🪥": "Razor",
    "🪒": "Safety Razor",
    "🧺": "Basket",
    "🧦": "Socks",
    "🧤": "Gloves",
    "🧣": "Scarf",
    "👖": "Jeans",
    "👕": "T-Shirt",
    "👚": "Woman’s Clothes",
    "👔": "Necktie",
    "👗": "Dress",
    "👘": "Kimono",
    "🥻": "Sari",
    "👙": "Bikini",
    "🩳": "Shorts",
    "🩲": "Briefs",
    "🧥": "Coat",
    "🥼": "Lab Coat",
    "🦺": "Safety Vest",
    "⛑️": "Rescue Worker’s Helmet",
    "🪖": "Military Helmet",
    "🎓": "Graduation Cap",
    "👒": "Woman's Hat",
    "🧢": "Billed Cap",
    "👑": "Crown",
    "🎒": "School Backpack",
    "👝": "Clutch Bag",
    "👛": "Purse",
    "👜": "Handbag",
    "💼": "Briefcase",
    "☂️": "Umbrella",
    "🌂": "Umbrella with Rain Drops",
    "💍": "Ring",
    "💎": "Gem Stone",
    "💄": "Lipstick",
    "👠": "High-Heeled Shoe",
    "👟": "Running Shoe",
    "👞": "Man's Shoe",
    "🥿": "Flat Shoe",
    "🩴": "Thong Sandal",
    "👡": "Woman's Sandal",
    "👢": "Woman's Boot",
    "🥾": "Hiking Boot",
    "🦯": "White Cane",
    "🕶️": "Sunglasses",
    "👓": "Glasses",
    "🥽": "Goggles",
    "⚗️": "Alembic",
    "🧫": "Petri Dish",
    "🧪": "Test Tube",
    "💉": "Syringe",
    "💊": "Pill",
    "🩹": "Adhesive Bandage",
    "🩺": "Stethoscope",
    "🧬": "DNA Double Helix",
    "🔭": "Telescope",
    "🔬": "Microscope",
    "📡": "Satellite Antenna",
    "🛰️": "Satellite",
    "🧯": "Fire Extinguisher",
    "🪓": "Axe",
    "🪜": "Ladder",
    "🪣": "Boat Hook",
    "🪝": "Hook",
    "🧲": "Magnet",
    "🧰": "Toolbox",
    "🗜️": "Clamp",
    "🔩": "Nut and Bolt",
    "🪛": "Screw",
    "🪚": "Razor Blade",
    "🔧": "Wrench",
    "🔨": "Hammer",
    "⚒️": "Hammer and Pick",
    "🛠️": "Hammer and Wrench",
    "⛏️": "Pick",
    "⚙️": "Gear",
    "🔗": "Link",
    "⛓️": "Chains",
    "📎": "Paperclip",
    "🖇️": "Linked Paperclips",
    "📏": "Straight Ruler",
    "📐": "Triangular Ruler",
    "🖊️": "Fountain Pen",
    "🖋️": "Pen",
    "✒️": "Black Nib",
    "✏️": "Pencil",
    "📝": "Memo",
    "📖": "Open Book",
    "📚": "Books",
    "📒": "Ledger",
    "📔": "Notebook",
    "📕": "Closed Book",
    "📓": "Notebook with Decorative Cover",
    "📗": "Green Book",
    "📘": "Blue Book",
    "📙": "Orange Book",
    "🔖": "Bookmark",
    "🗒️": "Spiral Notepad",
    "📄": "Page Facing Up",
    "📃": "Page with Curl",
    "📋": "Clipboard",
    "📑": "Bookmark Tabs",
    "📂": "File Folder",
    "📁": "Open File Folder",
    "🗂️": "File Cabinet",
    "🗃️": "Card File Box",
    "🗄️": "File Cabinet",
    "📊": "Bar Chart",
    "📈": "Chart Increasing",
    "📉": "Chart Decreasing",
    "📇": "Card Index",
    "📌": "Pushpin",
    "📍": "Round Pushpin",
    "✂️": "Scissors",
    "🗑️": "Wastebasket",
    "📰": "Newspaper",
    "🗞️": "Rolled-Up Newspaper",
    "🏷️": "Label",
    "📦": "Package",
    "📫": "Mailbox",
    "📪": "Mailbox with Raised Flag",
    "📬": "Open Mailbox with Raised Flag",
    "📭": "Open Mailbox with Lowered Flag",
    "✉️": "Envelope",
    "📧": "E-Mail",
    "📩": "Envelope with Arrow",
    "📨": "Incoming Envelope",
    "📤": "Outbox Tray",
    "📥": "Inbox Tray",
    "🗳️": "Ballot Box with Ballot",
    "🕛": "Twelve O'Clock",
    "🕧": "Twelve-Thirty",
    "🕐": "One O'Clock",
    "🕜": "One-Thirty",
    "🕑": "Two O'Clock",
    "🕝": "Two-Thirty",
    "🕒": "Three O'Clock",
    "🕞": "Three-Thirty",
    "🕓": "Four O'Clock",
    "🕟": "Four-Thirty",
    "🕔": "Five O'Clock",
    "🕠": "Five-Thirty",
    "🕕": "Six O'Clock",
    "🕡": "Six-Thirty",
    "🕖": "Seven O'Clock",
    "🕢": "Seven-Thirty",
    "🕗": "Eight O'Clock",
    "🕣": "Eight-Thirty",
    "🕘": "Nine O'Clock",
    "🕤": "Nine-Thirty",
    "🕙": "Ten O'Clock",
    "🕥": "Ten-Thirty",
    "🕚": "Eleven O'Clock",
    "🕦": "Eleven-Thirty",
    "⏱️": "Stopwatch",
    "⌚": "Watch",
    "🕰️": "Mantelpiece Clock",
    "⌛": "Hourglass Done",
    "⏳": "Hourglass Not Done",
    "⏲️": "Timer Clock",
    "⏰": "Alarm Clock",
    "📅": "Tear-Off Calendar",
    "📆": "Desk Calendar",
    "🗓️": "Spiral Calendar",
    "🪧": "Litter in Bin Sign",
    "🛎️": "Bellhop Bell",
    "🔔": "Bell",
    "📯": "Postal Horn",
    "📣": "Megaphone",
    "🔍": "Left-Pointing Magnifying Glass",
    "🔎": "Right-Pointing Magnifying Glass",
    "🔮": "Crystal Ball",
    "🧿": "Nazar Amulet",
    "📿": "Prayer Beads",
    "🏺": "Amphora",
    "⚱️": "Funeral Urn",
    "⚰️": "Coffin",
    "🪦": "Headstone",
    "🚬": "Cigarette",
    "💣": "Bomb",
    "🪤": "Mouse Trap",
    "📜": "Scroll",
    "⚔️": "Crossed Swords",
    "🗡️": "Dagger",
    "🛡️": "Shield",
    "🗝️": "Old Key",
    "🔑": "Key",
    "🔐": "Locked",
    "🔏": "Lock with Ink Pen",
    "🔒": "Locked with Key",
    "🔓": "Unlocked",
    "⬛": "Black Large Square",
    "⬜": "White Large Square",
    "♥": "Black Heart Suit",
    "♦": "Black Diamond Suit",
    "♣": "Black Club Suit",
    "♠": "Black Spade Suit",
    "♈": "Aries",
    "♉": "Taurus",
    "♊": "Gemini",
    "♋": "Cancer",
    "♌": "Leo",
    "♍": "Virgo",
    "♎": "Libra",
    "♏": "Scorpio",
    "♐": "Sagittarius",
    "♑": "Capricorn",
    "♒": "Aquarius",
    "♓": "Pisces",
    "⛎": "Ophiuchus",
    "♀": "Female Sign",
    "♂": "Male Sign",
    "⚧": "Transgender Symbol",
    "💭": "Thought Balloon",
    "🗯": "Right Anger Bubble",
    "💬": "Speech Balloon",
    "🗨": "Left Speech Bubble",
    "❕": "White Exclamation Mark",
    "❗": "Heavy Exclamation Mark",
    "❔": "White Question Mark",
    "❓": "Heavy Question Mark",
    "⁉": "Exclamation Question Mark",
    "‼": "Double Exclamation Mark",
    "⭕": "Heavy Large Circle",
    "❌": "Cross Mark",
    "🚫": "No Entry Sign",
    "🚳": "No Bicycles",
    "🚭": "No Smoking",
    "🚯": "No Littering",
    "🚱": "Non-Potable Water",
    "🚷": "No Pedestrians",
    "📵": "No Mobile Phones",
    "🔞": "No One Under Eighteen",
    "🔕": "Bell with Slash",
    "🔇": "Muted Speaker",
    "🅰": "A Button (Blood Type)",
    "🆎": "AB Button (Blood Type)",
    "🅱": "B Button (Blood Type)",
    "🅾": "O Button (Blood Type)",
    "🆑": "CL Button",
    "🆘": "SOS Button",
    "⛔": "No Entry",
    "📛": "Name Badge",
    "♨": "Hot Springs",
    "💢": "Anger Symbol",
    "🔻": "Red Triangle Pointed Down",
    "🔺": "Red Triangle Pointed Up",
    "🉐": "Japanese “Bargain” Button",
    "㊙": "Japanese “Secret” Button",
    "㊗": "Japanese “Congratulations” Button",
    "🈴": "Japanese “Passing Grade” Button",
    "🈵": "Japanese “No Vacancy” Button",
    "🈹": "Japanese “Discount” Button",
    "🈲": "Japanese “Prohibited” Button",
    "🉑": "Japanese “Acceptable” Button",
    "🈶": "Japanese “Not Free of Charge” Button",
    "🈚": "Japanese “Free of Charge” Button",
    "🈸": "Japanese “Application” Button",
    "🈺": "Japanese “Open for Business” Button",
    "🈷": "Japanese “Monthly Amount” Button",
    "✴": "Eight-Pointed Star",
    "🔶": "Large Orange Diamond",
    "🔸": "Small Orange Diamond",
    "🔆": "Bright Button",
    "🔅": "Dim Button",
    "🆚": "VS Button",
    "🎦": "Cinema",
    "📶": "Antenna Bars",
    "🔁": "Repeat Button",
    "🔂": "Repeat Single Button",
    "🔀": "Shuffle Tracks Button",
    "▶": "Play Button",
    "⏩": "Fast-Forward Button",
    "⏭": "Next Track Button",
    "⏯": "Play or Pause Button",
    "◀": "Reverse Button",
    "⏪": "Fast Reverse Button",
    "⏮": "Last Track Button",
    "🔼": "Upwards Button",
    "⏫": "Fast Up Button",
    "🔽": "Downwards Button",
    "⏬": "Fast Down Button",
    "⏸": "Pause Button",
    "⏹": "Stop Button",
    "⏺": "Record Button",
    "⏏": "Eject Button",
    "📴": "Mobile Phone Off",
    "📳": "Vibration Mode",
    "📲": "Mobile Phone",
    "🔈": "Speaker Low Volume",
    "🔉": "Speaker Medium Volume",
    "🔊": "Speaker High Volume",
    "🎼": "Musical Score",
    "🎵": "Musical Note",
    "🎶": "Musical Notes",
    "☢": "Radioactive Sign",
    "☣": "Biohazard Sign",
    "⚠": "Warning Sign",
    "🚸": "Children Crossing",
    "⚜": "Fleur-De-Lis",
    "🔱": "Trident Emblem",
    "〽": "Part Alternation Mark",
    "🔰": "Japanese “Beginner” Button",
    "✳": "Eight Spoked Asterisk",
    "❇": "Sparkle",
    "♻": "Recycling Symbol",
    "💱": "Currency Exchange",
    "💲": "Heavy Dollar Sign",
    "💹": "Chart Increasing with Yen Sign",
    "🈯": "Japanese “Reserved” Button",
    "❎": "Cross Mark Button",
    "✅": "White Heavy Check Mark",
    "✔": "Heavy Check Mark",
    "☑": "Ballot Box with Check",
    "⬆": "Upwards Arrow",
    "↗": "Up-Right Arrow",
    "➡": "Right Arrow",
    "↘": "Down-Right Arrow",
    "⬇": "Downwards Arrow",
    "↙": "Down-Left Arrow",
    "⬅": "Left Arrow",
    "↖": "Up-Left Arrow",
    "↕": "Up-Down Arrow",
    "↔": "Left-Right Arrow",
    "↩": "Right Arrow Curving Left",
    "↪": "Right Arrow Curving Right",
    "⤴": "Right Arrow Curving Up",
    "⤵": "Right Arrow Curving Down",
    "🔃": "Clockwise Vertical Arrows",
    "🔄": "Anticlockwise Arrows Button",
    "🔙": "Back Arrow",
    "🔛": "On! Arrow",
    "🔝": "Top Arrow",
    "🔚": "End Arrow",
    "🔜": "Soon Arrow",
    "🆕": "New Button",
    "🆓": "Free Button",
    "🆙": "Up! Button",
    "🆗": "OK Button",
    "🆒": "Cool Button",
    "🆖": "NG Button",
    "ℹ": "Information",
    "🅿": "P Button",
    "🈁": "Japanese “Here” Button",
    "🈂": "Japanese “Service Charge” Button",
    "🈳": "Japanese “No Vacancy” Button",
    "🔣": "Input Symbol for Symbols",
    "🔤": "Input Symbol for Latin Letters",
    "🔠": "Input Symbol for Latin Capital Letters",
    "🔡": "Input Symbol for Latin Small Letters",
    "🔢": "Input Symbol for Numbers",
    "#️⃣": "Keycap Number Sign",
    "*️⃣": "Keycap Asterisk",
    "0️⃣": "Keycap 0",
    "1️⃣": "Keycap 1",
    "2️⃣": "Keycap 2",
    "3️⃣": "Keycap 3",
    "4️⃣": "Keycap 4",
    "5️⃣": "Keycap 5",
    "6️⃣": "Keycap 6",
    "7️⃣": "Keycap 7",
    "8️⃣": "Keycap 8",
    "9️⃣": "Keycap 9",
    "🔟": "Keycap 10",
    "💠": "Diamond with a Dot",
    "🔷": "Large Blue Diamond",
    "🔹": "Small Blue Diamond",
    "🏧": "ATM Sign",
    "Ⓜ": "Circled M",
    "🚾": "Water Closet",
    "🚻": "Restroom",
    "🚺": "Women’s Room",
    "♿": "Wheelchair Symbol",
    "🚼": "Baby Symbol",
    "🛗": "Elevator",
    "🚮": "Litter in Bin Sign",
    "🚰": "Potable Water",
    "🛂": "Passport Control",
    "🛃": "Customs",
    "🛅": "Baggage Claim",
    "⚛": "Atom Symbol",
    "🛐": "Place of Worship",
    "🕉": "Om",
    "☸": "Wheel of Dharma",
    "☮": "Peace Symbol",
    "☯": "Yin Yang",
    "✝": "Latin Cross",
    "☦": "Orthodox Cross",
    "✡": "Star of David",
    "🔯": "Dotted Six-Pointed Star",
    "🕎": "Menorah",
    "♾": "Infinity",
    "🆔": "ID Button",
    "⚕": "Medical Symbol",
    "✖": "Heavy Multiplication X",
    "➕": "Heavy Plus Sign",
    "➖": "Heavy Minus Sign",
    "➗": "Heavy Division Sign",
    "➰": "Curly Loop",
    "➿": "Double Curly Loop",
    "〰": "Wavy Dash",
    "©": "Copyright Sign",
    "®": "Registered Sign",
    "™": "Trade Mark Sign",
    "🔘": "Radio Button",
    "🔳": "White Square Button",
    "◼": "Black Medium Square",
    "◾": "Black Medium-Small Square",
    "▪": "Black Small Square",
    "🔲": "Black Square Button",
    "◻": "White Medium Square",
    "◽": "White Medium-Small Square",
    "▫": "White Small Square",
    "👁‍🗨": "Eye in Speech Bubble",
    "🏁": "Chequered Flag",
    "🚩": "Triangular Flag",
    "🎌": "Crossed Flags",
    "🏴": "Black Flag",
    "🏳": "White Flag",
    "🏳‍🌈": "Rainbow Flag",
    "🏳‍⚧": "Transgender Flag",
    "🏴‍☠": "Pirate Flag",
        "🇮🇲": "Isle of Man",
        "🇮🇳": "India",
        "🇮🇴": "British Indian Ocean Territory",
        "🇮🇶": "Iraq",
        "🇮🇷": "Iran",
        "🇮🇸": "Iceland",
        "🇮🇹": "Italy",
        "🇯🇪": "Jersey",
        "🇯🇲": "Jamaica",
        "🇯🇴": "Jordan",
        "🇯🇵": "Japan",
        "🇰🇪": "Kenya",
        "🇰🇬": "Kyrgyzstan",
        "🇰🇭": "Cambodia",
        "🇰🇮": "Kiribati",
        "🇰🇰": "Cocos (Keeling) Islands",
        "🇰🇲": "Comoros",
        "🇰🇳": "St. Kitts & Nevis",
        "🇰🇵": "North Korea",
        "🇰🇷": "South Korea",
        "🇰🇼": "Kuwait",
        "🇰🇾": "Cayman Islands",
        "🇰🇿": "Kazakhstan",
        "🇱🇦": "Laos",
        "🇱🇧": "Lebanon",
        "🇱🇨": "St. Lucia",
        "🇱🇮": "Liechtenstein",
        "🇱🇱": "Lithuania",
        "🇱🇲": "Luxembourg",
        "🇱🇰": "Sri Lanka",
        "🇱🇷": "Liberia",
        "🇱🇸": "Lesotho",
        "🇱🇹": "Lithuania",
        "🇱🇻": "Latvia",
        "🇱🇾": "Libya",
        "🇲🇦": "Morocco",
        "🇲🇨": "Monaco",
        "🇲🇩": "Moldova",
        "🇲🇪": "Montenegro",
        "🇲🇫": "St. Martin",
        "🇲🇬": "Madagascar",
        "🇲🇭": "Marshall Islands",
        "🇲🇰": "North Macedonia",
        "🇲🇱": "Mali",
        "🇲🇲": "Myanmar (Burma)",
        "🇲🇳": "Mongolia",
        "🇲🇴": "Macau SAR China",
        "🇲🇵": "Northern Mariana Islands",
        "🇲🇶": "Martinique",
        "🇲🇷": "Mauritania",
        "🇲🇸": "Montserrat",
        "🇲🇹": "Malta",
        "🇲🇺": "Mauritius",
        "🇲🇻": "Maldives",
        "🇲🇼": "Malawi",
        "🇲🇽": "Mexico",
        "🇲🇾": "Malaysia",
        "🇲🇿": "Mozambique",
        "🇳🇦": "Namibia",
        "🇳🇨": "New Caledonia",
        "🇳🇪": "Niger",
        "🇳🇫": "Norfolk Island",
        "🇳🇬": "Nigeria",
        "🇳🇮": "Nicaragua",
        "🇳🇱": "Netherlands",
        "🇳🇴": "Norway",
        "🇳🇵": "Nepal",
        "🇳🇷": "Nauru",
        "🇳🇺": "Niue",
        "🇳🇿": "New Zealand",
        "🇴🇲": "Oman",
        "🇵🇦": "Panama",
        "🇵🇪": "Peru",
        "🇵🇫": "French Polynesia",
        "🇵🇬": "Papua New Guinea",
        "🇵🇭": "Philippines",
        "🇵🇰": "Pakistan",
        "🇵🇱": "Poland",
        "🇵🇲": "St. Pierre & Miquelon",
        "🇵🇳": "Pitcairn Islands",
        "🇵🇷": "Puerto Rico",
        "🇵🇸": "Palestinian Territories",
        "🇵🇹": "Portugal",
        "🇵🇼": "Palau",
        "🇵🇾": "Paraguay",
        "🇶🇦": "Qatar",
        "🇷🇪": "Réunion",
        "🇷🇴": "Romania",
        "🇷🇸": "Serbia",
        "🇷🇺": "Russia",
        "🇷🇼": "Rwanda",
        "🇸🇦": "Saudi Arabia",
        "🇸🇧": "Solomon Islands",
        "🇸🇨": "Seychelles",
        "🇸🇩": "Sudan",
        "🇸🇪": "Sweden",
        "🇸🇬": "Singapore",
        "🇸🇭": "St. Helena",
        "🇸🇮": "Slovenia",
        "🇸🇯": "Svalbard & Jan Mayen",
        "🇸🇰": "Slovakia",
        "🇸🇱": "Sierra Leone",
        "🇸🇲": "San Marino",
        "🇸🇳": "Senegal",
        "🇸🇴": "Somalia",
        "🇸🇷": "Suriname",
        "🇸🇸": "South Sudan",
        "🇸🇹": "São Tomé & Príncipe",
        "🇸🇻": "El Salvador",
        "🇸🇽": "Sint Maarten",
        "🇸🇾": "Syria",
        "🇸🇿": "Eswatini",
        "🇹🇦": "Tristan da Cunha",
        "🇹🇨": "Turks & Caicos Islands",
        "🇹🇩": "Chad",
        "🇹🇫": "French Southern Territories",
        "🇹🇬": "Togo",
        "🇹🇭": "Thailand",
        "🇹🇯": "Tajikistan",
        "🇹🇰": "Tokelau",
        "🇹🇱": "Timor-Leste",
        "🇹🇲": "Turkmenistan",
        "🇹🇳": "Tunisia",
        "🇹🇴": "Tonga",
        "🇹🇷": "Turkey",
        "🇹🇹": "Trinidad & Tobago",
        "🇹🇻": "Tuvalu",
        "🇹🇼": "Taiwan",
        "🇹🇿": "Tanzania",
        "🇺🇦": "Ukraine",
        "🇺🇬": "Uganda",
        "🇺🇲": "U.S. Outlying Islands",
        "🇺🇳": "United Nations",
        "🇺🇸": "United States",
        "🇺🇾": "Uruguay",
        "🇺🇿": "Uzbekistan",
        "🇻🇦": "Vatican City",
        "🇻🇨": "St. Vincent & Grenadines",
        "🇻🇪": "Venezuela",
        "🇻🇬": "British Virgin Islands",
        "🇻🇮": "U.S. Virgin Islands",
        "🇻🇳": "Vietnam",
        "🇻🇺": "Vanuatu",
        "🇼🇫": "Wallis & Futuna",
        "🇼🇸": "Samoa",
        "🇽🇰": "Kosovo",
        "🇾🇪": "Yemen",
        "🇾🇹": "Mayotte",
        "🇿🇦": "South Africa",
        "🇿🇲": "Zambia",
        "🇿🇼": "Zimbabwe",
        "⿬": "Dungan",
        "⿮": "Nushu",
        "⿭": "Shuishu",
        "🇲🇮": "Montserrat",
        "🇳🇮": "Nicaragua",
        "🇳🇱": "Netherlands",
        "🇳🇴": "Norway",
        "🇳🇵": "Nepal",
        "🇳🇷": "Nauru",
        "🇳🇺": "Niue",
        "🇳🇿": "New Zealand",
        "🇴🇲": "Oman",
        "🇵🇦": "Panama",
        "🇵🇪": "Peru",
        "🇵🇫": "French Polynesia",
        "🇵🇬": "Papua New Guinea",
        "🇵🇭": "Philippines",
        "🇵🇰": "Pakistan",
        "🇵🇱": "Poland",
        "🇵🇲": "St. Pierre & Miquelon",
        "🇵🇳": "Pitcairn Islands",
        "🇵🇷": "Puerto Rico",
        "🇵🇸": "Palestinian Territories",
        "🇵🇹": "Portugal",
        "🇵🇼": "Palau",
        "🇵🇾": "Paraguay",
        "🇶🇦": "Qatar",
        "🇷🇪": "Réunion",
        "🇷🇴": "Romania",
        "🇷🇸": "Serbia",
        "🇷🇺": "Russia",
        "🇷🇼": "Rwanda",
        "🇸🇦": "Saudi Arabia",
        "🇸🇧": "Solomon Islands",
        "🇸🇨": "Seychelles",
        "🇸🇩": "Sudan",
        "🇸🇪": "Sweden",
        "🇸🇬": "Singapore",
        "🇸🇭": "St. Helena",
        "🇸🇮": "Slovenia",
        "🇸🇯": "Svalbard & Jan Mayen",
        "🇸🇰": "Slovakia",
        "🇸🇱": "Sierra Leone",
        "🇸🇲": "San Marino",
        "🇸🇳": "Senegal",
        "🇸🇴": "Somalia",
        "🇸🇷": "Suriname",
        "🇸🇸": "South Sudan",
        "🇸🇹": "São Tomé & Príncipe",
        "🇸🇻": "El Salvador",
        "🇸🇽": "Sint Maarten",
        "🇸🇾": "Syria",
        "🇸🇿": "Eswatini",
        "🇹🇦": "Tristan da Cunha",
        "🇹🇨": "Turks & Caicos Islands",
        "🇹🇩": "Chad",
        "🇹🇫": "French Southern Territories",
        "🇹🇬": "Togo",
        "🇹🇭": "Thailand",
        "🇹🇯": "Tajikistan",
        "🇹🇰": "Tokelau",
        "🇹🇱": "Timor-Leste",
        "🇹🇲": "Turkmenistan",
        "🇹🇳": "Tunisia",
        "🇹🇴": "Tonga",
        "🇹🇷": "Turkey",
        "🇹🇹": "Trinidad & Tobago",
        "🇹🇻": "Tuvalu",
        "🇹🇼": "Taiwan",
        "🇹🇿": "Tanzania",
        "🇺🇦": "Ukraine",
        "🇺🇬": "Uganda",
        "🇺🇲": "U.S. Outlying Islands",
        "🇺🇳": "United Nations",
        "🇺🇸": "United States",
        "🇺🇾": "Uruguay",
        "🇺🇿": "Uzbekistan",
        "🇻🇦": "Vatican City",
        "🇻🇨": "St. Vincent & Grenadines",
        "🇻🇪": "Venezuela",
        "🇻🇬": "British Virgin Islands",
        "🇻🇮": "U.S. Virgin Islands",
        "🇻🇳": "Vietnam",
        "🇻🇺": "Vanuatu",
        "🇼🇫": "Wallis & Futuna",
        "🇼🇸": "Samoa",
        "🇽🇰": "Kosovo",
        "🇾🇪": "Yemen",
        "🇾🇹": "Mayotte",
        "🇿🇦": "South Africa",
        "🇿🇲": "Zambia",
        "🇿🇼": "Zimbabwe",
        "⿬": "Dungan",
        "⿮": "Nushu",
        "⿭": "Shuishu",
        "🇦🇹": "Austria",
        "🇨🇹": "Central African Republic",
        "🇩🇹": "Diego Garcia",
        "🇹🇫": "French Southern Territories",
        "🇹🇬": "Togo",
        "🇹🇭": "Thailand",
        "🇹🇯": "Tajikistan",
        "🇹🇰": "Turkmenistan",
        "🇹🇱": "Timor-Leste",
        "🇹🇲": "Turkmenistan",
        "🇹🇳": "Tunisia",
        "🇹🇴": "Tonga",
        "🇹🇷": "Turkey",
        "🇹🇹": "Trinidad & Tobago",
        "🇹🇻": "Tuvalu",
        "🇹🇼": "Taiwan",
        "🇹🇿": "Tanzania",
        "🇺🇦": "Ukraine",
        "🇺🇬": "Uganda",
        "🇺🇲": "U.S. Outlying Islands",
        "🇺🇳": "United Nations",
        "🇺🇸": "United States",
        "🇺🇾": "Uruguay",
        "🇺🇿": "Uzbekistan",
        "🇻🇦": "Vatican City",
        "🇻🇨": "St. Vincent & Grenadines",
        "🇻🇪": "Venezuela",
        "🇻🇬": "British Virgin Islands",
        "🇻🇮": "U.S. Virgin Islands",
        "🇻🇳": "Vietnam",
        "🇻🇺": "Vanuatu",
        "🇼🇫": "Wallis & Futuna",
        "🇼🇸": "Samoa",
        "🇽🇰": "Kosovo",
        "🇾🇪": "Yemen",
        "🇾🇹": "Mayotte",
        "🇿🇦": "South Africa",
        "🇿🇲": "Zambia",
        "🇿🇼": "Zimbabwe",
        "🏴󠁧󠁢󠁥󠁮󠁧󠁿": "England",
        "🏴󠁧󠁢󠁳󠁣󠁴󠁿": "Scotland",
        "🏴󠁧󠁢󠁷󠁬󠁳󠁿": "Wales"
     }

        self.meaning_to_emoji = {v: k for k, v in self.emoji_data.items()}

    def get_meaning(self, emoji_or_meaning):
        if emoji_or_meaning in self.emoji_data:
            return self.emoji_data.get(emoji_or_meaning, "Emoji not found")
        elif emoji_or_meaning in self.meaning_to_emoji:
            return self.meaning_to_emoji.get(emoji_or_meaning, "Meaning not found")
        else:
            return "Emoji or meaning not found"

emoji_meaning = EmojiMeaning()
 