# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PatchedAddOnUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'addon_name': 'str',
        'active_from': 'datetime',
        'active_to': 'datetime'
    }

    attribute_map = {
        'addon_name': 'addon_name',
        'active_from': 'active_from',
        'active_to': 'active_to'
    }

    def __init__(self, addon_name=None, active_from=None, active_to=None):  # noqa: E501
        """PatchedAddOnUpdateRequest - a model defined in Swagger"""  # noqa: E501
        self._addon_name = None
        self._active_from = None
        self._active_to = None
        self.discriminator = None
        if addon_name is not None:
            self.addon_name = addon_name
        if active_from is not None:
            self.active_from = active_from
        if active_to is not None:
            self.active_to = active_to

    @property
    def addon_name(self):
        """Gets the addon_name of this PatchedAddOnUpdateRequest.  # noqa: E501


        :return: The addon_name of this PatchedAddOnUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._addon_name

    @addon_name.setter
    def addon_name(self, addon_name):
        """Sets the addon_name of this PatchedAddOnUpdateRequest.


        :param addon_name: The addon_name of this PatchedAddOnUpdateRequest.  # noqa: E501
        :type: str
        """

        self._addon_name = addon_name

    @property
    def active_from(self):
        """Gets the active_from of this PatchedAddOnUpdateRequest.  # noqa: E501


        :return: The active_from of this PatchedAddOnUpdateRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._active_from

    @active_from.setter
    def active_from(self, active_from):
        """Sets the active_from of this PatchedAddOnUpdateRequest.


        :param active_from: The active_from of this PatchedAddOnUpdateRequest.  # noqa: E501
        :type: datetime
        """

        self._active_from = active_from

    @property
    def active_to(self):
        """Gets the active_to of this PatchedAddOnUpdateRequest.  # noqa: E501


        :return: The active_to of this PatchedAddOnUpdateRequest.  # noqa: E501
        :rtype: datetime
        """
        return self._active_to

    @active_to.setter
    def active_to(self, active_to):
        """Sets the active_to of this PatchedAddOnUpdateRequest.


        :param active_to: The active_to of this PatchedAddOnUpdateRequest.  # noqa: E501
        :type: datetime
        """

        self._active_to = active_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PatchedAddOnUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PatchedAddOnUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
