# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PaymentProcesorPostDataRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_processor': 'str',
        'data': 'dict(str, object)'
    }

    attribute_map = {
        'payment_processor': 'payment_processor',
        'data': 'data'
    }

    def __init__(self, payment_processor=None, data=None):  # noqa: E501
        """PaymentProcesorPostDataRequest - a model defined in Swagger"""  # noqa: E501
        self._payment_processor = None
        self._data = None
        self.discriminator = None
        self.payment_processor = payment_processor
        self.data = data

    @property
    def payment_processor(self):
        """Gets the payment_processor of this PaymentProcesorPostDataRequest.  # noqa: E501

        * `stripe` - Stripe * `braintree` - Braintree  # noqa: E501

        :return: The payment_processor of this PaymentProcesorPostDataRequest.  # noqa: E501
        :rtype: str
        """
        return self._payment_processor

    @payment_processor.setter
    def payment_processor(self, payment_processor):
        """Sets the payment_processor of this PaymentProcesorPostDataRequest.

        * `stripe` - Stripe * `braintree` - Braintree  # noqa: E501

        :param payment_processor: The payment_processor of this PaymentProcesorPostDataRequest.  # noqa: E501
        :type: str
        """
        if payment_processor is None:
            raise ValueError("Invalid value for `payment_processor`, must not be `None`")  # noqa: E501
        allowed_values = ["stripe", "braintree"]  # noqa: E501
        if payment_processor not in allowed_values:
            raise ValueError(
                "Invalid value for `payment_processor` ({0}), must be one of {1}"  # noqa: E501
                .format(payment_processor, allowed_values)
            )

        self._payment_processor = payment_processor

    @property
    def data(self):
        """Gets the data of this PaymentProcesorPostDataRequest.  # noqa: E501


        :return: The data of this PaymentProcesorPostDataRequest.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this PaymentProcesorPostDataRequest.


        :param data: The data of this PaymentProcesorPostDataRequest.  # noqa: E501
        :type: dict(str, object)
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentProcesorPostDataRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentProcesorPostDataRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
