# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PerPlanPerDay(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plan': 'LightweightPlanVersion',
        'revenue': 'str'
    }

    attribute_map = {
        'plan': 'plan',
        'revenue': 'revenue'
    }

    def __init__(self, plan=None, revenue=None):  # noqa: E501
        """PerPlanPerDay - a model defined in Swagger"""  # noqa: E501
        self._plan = None
        self._revenue = None
        self.discriminator = None
        self.plan = plan
        self.revenue = revenue

    @property
    def plan(self):
        """Gets the plan of this PerPlanPerDay.  # noqa: E501


        :return: The plan of this PerPlanPerDay.  # noqa: E501
        :rtype: LightweightPlanVersion
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this PerPlanPerDay.


        :param plan: The plan of this PerPlanPerDay.  # noqa: E501
        :type: LightweightPlanVersion
        """
        if plan is None:
            raise ValueError("Invalid value for `plan`, must not be `None`")  # noqa: E501

        self._plan = plan

    @property
    def revenue(self):
        """Gets the revenue of this PerPlanPerDay.  # noqa: E501


        :return: The revenue of this PerPlanPerDay.  # noqa: E501
        :rtype: str
        """
        return self._revenue

    @revenue.setter
    def revenue(self, revenue):
        """Sets the revenue of this PerPlanPerDay.


        :param revenue: The revenue of this PerPlanPerDay.  # noqa: E501
        :type: str
        """
        if revenue is None:
            raise ValueError("Invalid value for `revenue`, must not be `None`")  # noqa: E501

        self._revenue = revenue

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PerPlanPerDay, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PerPlanPerDay):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
