# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanVersionHistoricalSubscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer_id': 'str',
        'customer_name': 'str',
        'start_date': 'datetime',
        'end_date': 'datetime',
        'auto_renew': 'bool'
    }

    attribute_map = {
        'customer_id': 'customer_id',
        'customer_name': 'customer_name',
        'start_date': 'start_date',
        'end_date': 'end_date',
        'auto_renew': 'auto_renew'
    }

    def __init__(self, customer_id=None, customer_name=None, start_date=None, end_date=None, auto_renew=None):  # noqa: E501
        """PlanVersionHistoricalSubscription - a model defined in Swagger"""  # noqa: E501
        self._customer_id = None
        self._customer_name = None
        self._start_date = None
        self._end_date = None
        self._auto_renew = None
        self.discriminator = None
        self.customer_id = customer_id
        self.customer_name = customer_name
        self.start_date = start_date
        self.end_date = end_date
        self.auto_renew = auto_renew

    @property
    def customer_id(self):
        """Gets the customer_id of this PlanVersionHistoricalSubscription.  # noqa: E501


        :return: The customer_id of this PlanVersionHistoricalSubscription.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this PlanVersionHistoricalSubscription.


        :param customer_id: The customer_id of this PlanVersionHistoricalSubscription.  # noqa: E501
        :type: str
        """
        if customer_id is None:
            raise ValueError("Invalid value for `customer_id`, must not be `None`")  # noqa: E501

        self._customer_id = customer_id

    @property
    def customer_name(self):
        """Gets the customer_name of this PlanVersionHistoricalSubscription.  # noqa: E501


        :return: The customer_name of this PlanVersionHistoricalSubscription.  # noqa: E501
        :rtype: str
        """
        return self._customer_name

    @customer_name.setter
    def customer_name(self, customer_name):
        """Sets the customer_name of this PlanVersionHistoricalSubscription.


        :param customer_name: The customer_name of this PlanVersionHistoricalSubscription.  # noqa: E501
        :type: str
        """
        if customer_name is None:
            raise ValueError("Invalid value for `customer_name`, must not be `None`")  # noqa: E501

        self._customer_name = customer_name

    @property
    def start_date(self):
        """Gets the start_date of this PlanVersionHistoricalSubscription.  # noqa: E501

        The time the subscription starts. This will be a string in yyyy-mm-dd HH:mm:ss format in UTC time.  # noqa: E501

        :return: The start_date of this PlanVersionHistoricalSubscription.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this PlanVersionHistoricalSubscription.

        The time the subscription starts. This will be a string in yyyy-mm-dd HH:mm:ss format in UTC time.  # noqa: E501

        :param start_date: The start_date of this PlanVersionHistoricalSubscription.  # noqa: E501
        :type: datetime
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this PlanVersionHistoricalSubscription.  # noqa: E501

        The time the subscription starts. This will be a string in yyyy-mm-dd HH:mm:ss format in UTC time.  # noqa: E501

        :return: The end_date of this PlanVersionHistoricalSubscription.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this PlanVersionHistoricalSubscription.

        The time the subscription starts. This will be a string in yyyy-mm-dd HH:mm:ss format in UTC time.  # noqa: E501

        :param end_date: The end_date of this PlanVersionHistoricalSubscription.  # noqa: E501
        :type: datetime
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def auto_renew(self):
        """Gets the auto_renew of this PlanVersionHistoricalSubscription.  # noqa: E501

        Whether the subscription automatically renews. Defaults to true.  # noqa: E501

        :return: The auto_renew of this PlanVersionHistoricalSubscription.  # noqa: E501
        :rtype: bool
        """
        return self._auto_renew

    @auto_renew.setter
    def auto_renew(self, auto_renew):
        """Sets the auto_renew of this PlanVersionHistoricalSubscription.

        Whether the subscription automatically renews. Defaults to true.  # noqa: E501

        :param auto_renew: The auto_renew of this PlanVersionHistoricalSubscription.  # noqa: E501
        :type: bool
        """
        if auto_renew is None:
            raise ValueError("Invalid value for `auto_renew`, must not be `None`")  # noqa: E501

        self._auto_renew = auto_renew

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanVersionHistoricalSubscription, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanVersionHistoricalSubscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
