# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SingleCRMProvider(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'crm_provider_name': 'str',
        'connected': 'bool',
        'self_hosted': 'bool',
        'working': 'bool',
        'connection_id': 'str',
        'account_id': 'str',
        'native_org_url': 'str'
    }

    attribute_map = {
        'crm_provider_name': 'crm_provider_name',
        'connected': 'connected',
        'self_hosted': 'self_hosted',
        'working': 'working',
        'connection_id': 'connection_id',
        'account_id': 'account_id',
        'native_org_url': 'native_org_url'
    }

    def __init__(self, crm_provider_name=None, connected=None, self_hosted=None, working=None, connection_id=None, account_id=None, native_org_url=None):  # noqa: E501
        """SingleCRMProvider - a model defined in Swagger"""  # noqa: E501
        self._crm_provider_name = None
        self._connected = None
        self._self_hosted = None
        self._working = None
        self._connection_id = None
        self._account_id = None
        self._native_org_url = None
        self.discriminator = None
        self.crm_provider_name = crm_provider_name
        self.connected = connected
        self.self_hosted = self_hosted
        self.working = working
        self.connection_id = connection_id
        self.account_id = account_id
        self.native_org_url = native_org_url

    @property
    def crm_provider_name(self):
        """Gets the crm_provider_name of this SingleCRMProvider.  # noqa: E501

        * `salesforce` - salesforce  # noqa: E501

        :return: The crm_provider_name of this SingleCRMProvider.  # noqa: E501
        :rtype: str
        """
        return self._crm_provider_name

    @crm_provider_name.setter
    def crm_provider_name(self, crm_provider_name):
        """Sets the crm_provider_name of this SingleCRMProvider.

        * `salesforce` - salesforce  # noqa: E501

        :param crm_provider_name: The crm_provider_name of this SingleCRMProvider.  # noqa: E501
        :type: str
        """
        if crm_provider_name is None:
            raise ValueError("Invalid value for `crm_provider_name`, must not be `None`")  # noqa: E501
        allowed_values = ["salesforce"]  # noqa: E501
        if crm_provider_name not in allowed_values:
            raise ValueError(
                "Invalid value for `crm_provider_name` ({0}), must be one of {1}"  # noqa: E501
                .format(crm_provider_name, allowed_values)
            )

        self._crm_provider_name = crm_provider_name

    @property
    def connected(self):
        """Gets the connected of this SingleCRMProvider.  # noqa: E501


        :return: The connected of this SingleCRMProvider.  # noqa: E501
        :rtype: bool
        """
        return self._connected

    @connected.setter
    def connected(self, connected):
        """Sets the connected of this SingleCRMProvider.


        :param connected: The connected of this SingleCRMProvider.  # noqa: E501
        :type: bool
        """
        if connected is None:
            raise ValueError("Invalid value for `connected`, must not be `None`")  # noqa: E501

        self._connected = connected

    @property
    def self_hosted(self):
        """Gets the self_hosted of this SingleCRMProvider.  # noqa: E501


        :return: The self_hosted of this SingleCRMProvider.  # noqa: E501
        :rtype: bool
        """
        return self._self_hosted

    @self_hosted.setter
    def self_hosted(self, self_hosted):
        """Sets the self_hosted of this SingleCRMProvider.


        :param self_hosted: The self_hosted of this SingleCRMProvider.  # noqa: E501
        :type: bool
        """
        if self_hosted is None:
            raise ValueError("Invalid value for `self_hosted`, must not be `None`")  # noqa: E501

        self._self_hosted = self_hosted

    @property
    def working(self):
        """Gets the working of this SingleCRMProvider.  # noqa: E501


        :return: The working of this SingleCRMProvider.  # noqa: E501
        :rtype: bool
        """
        return self._working

    @working.setter
    def working(self, working):
        """Sets the working of this SingleCRMProvider.


        :param working: The working of this SingleCRMProvider.  # noqa: E501
        :type: bool
        """
        if working is None:
            raise ValueError("Invalid value for `working`, must not be `None`")  # noqa: E501

        self._working = working

    @property
    def connection_id(self):
        """Gets the connection_id of this SingleCRMProvider.  # noqa: E501


        :return: The connection_id of this SingleCRMProvider.  # noqa: E501
        :rtype: str
        """
        return self._connection_id

    @connection_id.setter
    def connection_id(self, connection_id):
        """Sets the connection_id of this SingleCRMProvider.


        :param connection_id: The connection_id of this SingleCRMProvider.  # noqa: E501
        :type: str
        """
        if connection_id is None:
            raise ValueError("Invalid value for `connection_id`, must not be `None`")  # noqa: E501

        self._connection_id = connection_id

    @property
    def account_id(self):
        """Gets the account_id of this SingleCRMProvider.  # noqa: E501


        :return: The account_id of this SingleCRMProvider.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this SingleCRMProvider.


        :param account_id: The account_id of this SingleCRMProvider.  # noqa: E501
        :type: str
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def native_org_url(self):
        """Gets the native_org_url of this SingleCRMProvider.  # noqa: E501


        :return: The native_org_url of this SingleCRMProvider.  # noqa: E501
        :rtype: str
        """
        return self._native_org_url

    @native_org_url.setter
    def native_org_url(self, native_org_url):
        """Sets the native_org_url of this SingleCRMProvider.


        :param native_org_url: The native_org_url of this SingleCRMProvider.  # noqa: E501
        :type: str
        """
        if native_org_url is None:
            raise ValueError("Invalid value for `native_org_url`, must not be `None`")  # noqa: E501

        self._native_org_url = native_org_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SingleCRMProvider, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SingleCRMProvider):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
