
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-31T15:06:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cad296f02850888c697f9fc8955292c22a10e89",
 "version": "v0.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
