from _typeshed import Incomplete

class Finding:
    actions: Incomplete
    n_states: Incomplete
    currentS: int
    def __init__(self, length: int = ...) -> None: ...
    def reset(self): ...
    def step(self, action): ...
    def render(self) -> None: ...
