# Form implementation generated from reading ui file 'src/eric7/Plugins/CheckerPlugins/SyntaxChecker/SyntaxCheckerDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SyntaxCheckerDialog(object):
    def setupUi(self, SyntaxCheckerDialog):
        SyntaxCheckerDialog.setObjectName("SyntaxCheckerDialog")
        SyntaxCheckerDialog.resize(650, 600)
        SyntaxCheckerDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SyntaxCheckerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterFrame = QtWidgets.QFrame(parent=SyntaxCheckerDialog)
        self.filterFrame.setObjectName("filterFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.filterFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.filterFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.excludeFilesEdit = QtWidgets.QLineEdit(parent=self.filterFrame)
        self.excludeFilesEdit.setClearButtonEnabled(True)
        self.excludeFilesEdit.setObjectName("excludeFilesEdit")
        self.gridLayout.addWidget(self.excludeFilesEdit, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.filterFrame)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 2, 1)
        self.startButton = QtWidgets.QPushButton(parent=self.filterFrame)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.filterFrame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.builtinsEdit = QtWidgets.QLineEdit(parent=self.filterFrame)
        self.builtinsEdit.setClearButtonEnabled(True)
        self.builtinsEdit.setObjectName("builtinsEdit")
        self.gridLayout.addWidget(self.builtinsEdit, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.filterFrame)
        self.resultList = QtWidgets.QTreeWidget(parent=SyntaxCheckerDialog)
        self.resultList.setAlternatingRowColors(True)
        self.resultList.setObjectName("resultList")
        self.verticalLayout.addWidget(self.resultList)
        self.checkProgress = QtWidgets.QProgressBar(parent=SyntaxCheckerDialog)
        self.checkProgress.setProperty("value", 0)
        self.checkProgress.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.checkProgress.setObjectName("checkProgress")
        self.verticalLayout.addWidget(self.checkProgress)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SyntaxCheckerDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SyntaxCheckerDialog)
        QtCore.QMetaObject.connectSlotsByName(SyntaxCheckerDialog)
        SyntaxCheckerDialog.setTabOrder(self.excludeFilesEdit, self.builtinsEdit)
        SyntaxCheckerDialog.setTabOrder(self.builtinsEdit, self.startButton)
        SyntaxCheckerDialog.setTabOrder(self.startButton, self.resultList)

    def retranslateUi(self, SyntaxCheckerDialog):
        _translate = QtCore.QCoreApplication.translate
        SyntaxCheckerDialog.setWindowTitle(_translate("SyntaxCheckerDialog", "Syntax Check Result"))
        SyntaxCheckerDialog.setWhatsThis(_translate("SyntaxCheckerDialog", "<b>Syntax Check Results</b>\n"
"<p>This dialog shows the results of the syntax check. Double clicking an\n"
"entry will open an editor window and position the cursor at the respective line.</p>"))
        self.label_2.setText(_translate("SyntaxCheckerDialog", "Exclude Files:"))
        self.excludeFilesEdit.setToolTip(_translate("SyntaxCheckerDialog", "Enter filename patterns of files to be excluded separated by a comma"))
        self.startButton.setToolTip(_translate("SyntaxCheckerDialog", "Press to start the syntax check run"))
        self.startButton.setText(_translate("SyntaxCheckerDialog", "Start"))
        self.label_3.setText(_translate("SyntaxCheckerDialog", "Additional \'builtins\':"))
        self.builtinsEdit.setToolTip(_translate("SyntaxCheckerDialog", "Enter additional \'builtins\' names separated by whitespace."))
        self.resultList.setWhatsThis(_translate("SyntaxCheckerDialog", "<b>Result List</b>\n"
"<p>This list shows the results of the syntax check. Double clicking\n"
"an entry will open this entry in an editor window and position the cursor at\n"
"the respective line.</p>"))
        self.resultList.setSortingEnabled(True)
        self.resultList.headerItem().setText(0, _translate("SyntaxCheckerDialog", "File/Line"))
        self.resultList.headerItem().setText(1, _translate("SyntaxCheckerDialog", "Message"))
        self.resultList.headerItem().setText(2, _translate("SyntaxCheckerDialog", "Source"))
        self.checkProgress.setToolTip(_translate("SyntaxCheckerDialog", "Shows the progress of the syntax check action"))
        self.checkProgress.setFormat(_translate("SyntaxCheckerDialog", "%v/%m Files"))
