__version__ = "0.0.1"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00__init__.ipynb.

# %% auto 0
__all__ = ['lib', 'mods']

# %% ../nbs/00__init__.ipynb 3
from xtr import getalls, frommods, fromstars
lib, mods = 'ain', ('core', )
frommods(lib, mods, scope=globals())
fromstars(lib, mods, scope=globals())
__all__ = getalls(*tuple(globals().get(mod) for mod in mods))

# %% ../nbs/00__init__.ipynb 4
# core
# getalls(*mods)
# from itertools import chain

# from xtr import (atyp, util, tups, itrs, args, call, posx, strs, load,)
# from xtr.atyp import *
# from xtr.util import *
# from xtr.tups import *
# from xtr.itrs import *
# from xtr.args import *
# from xtr.call import *
# from xtr.posx import *
# from xtr.strs import *
# from xtr.load import *

# %% ../nbs/00__init__.ipynb 5
# __all__ = sorted(set(itertools.chain(*[
#     mod.__all__ for mod in (atyp, util, tups, itrs, args, call, posx, strs, load,)
# ])))
