
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-30T08:34:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "78a781f9c58a5b0e42a0fd1424ebe7e7e75fc62a",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
