__version__ = '0.1.1'
__title__ = 'zwdoc'
__description__ = 'Personal Python Utilities'
__url__ = 'https://github.com/njzhaowei/zwdoc'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2023 Zhao Wei. All rights reserved.'
