# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lotus_client
from lotus_client.models.add_feature_to_add_on_request import AddFeatureToAddOnRequest  # noqa: E501
from lotus_client.rest import ApiException


class TestAddFeatureToAddOnRequest(unittest.TestCase):
    """AddFeatureToAddOnRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddFeatureToAddOnRequest(self):
        """Test AddFeatureToAddOnRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lotus_client.models.add_feature_to_add_on_request.AddFeatureToAddOnRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
