# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lotus_client
from lotus_client.models.metric_access_per_subscription import MetricAccessPerSubscription  # noqa: E501
from lotus_client.rest import ApiException


class TestMetricAccessPerSubscription(unittest.TestCase):
    """MetricAccessPerSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetricAccessPerSubscription(self):
        """Test MetricAccessPerSubscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lotus_client.models.metric_access_per_subscription.MetricAccessPerSubscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
