# coding: utf-8

"""
    Lotus API

    Lotus is an open-core pricing and billing engine. We enable API companies to automate and optimize their custom usage-based pricing for any metric.  # noqa: E501

    OpenAPI spec version: 0.9.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lotus_client
from lotus_client.api.stripe_api import StripeApi  # noqa: E501
from lotus_client.rest import ApiException


class TestStripeApi(unittest.TestCase):
    """StripeApi unit test stubs"""

    def setUp(self):
        self.api = StripeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stripe_webhook_create(self):
        """Test case for stripe_webhook_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
