# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apps/media-recognition-service/client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+apps/media-recognition-service/client.proto\x12\x14media_recognition.v1\"C\n\x12RecognitionRequest\x12\x12\n\nfile_bytes\x18\x01 \x01(\x0c\x12\x19\n\x11message_record_id\x18\x02 \x01(\x04\"3\n\x13RecognitionResponse\x12\x12\n\x05\x65rror\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error2\xeb\x01\n\x17MediaRecognitionService\x12g\n\x0eRecognizeImage\x12(.media_recognition.v1.RecognitionRequest\x1a).media_recognition.v1.RecognitionResponse\"\x00\x12g\n\x0eRecognizeVideo\x12(.media_recognition.v1.RecognitionRequest\x1a).media_recognition.v1.RecognitionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apps.media_recognition_service.client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECOGNITIONREQUEST']._serialized_start=69
  _globals['_RECOGNITIONREQUEST']._serialized_end=136
  _globals['_RECOGNITIONRESPONSE']._serialized_start=138
  _globals['_RECOGNITIONRESPONSE']._serialized_end=189
  _globals['_MEDIARECOGNITIONSERVICE']._serialized_start=192
  _globals['_MEDIARECOGNITIONSERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
