# Generated by Django 4.2.4 on 2023-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
