from _typeshed import Incomplete

class PathFinding:
    window: Incomplete
    width: int
    unit: int
    height: int
    playerImgPath: Incomplete
    endImgPath: Incomplete
    actions: Incomplete
    n_actions: Incomplete
    def __init__(self) -> None: ...
    def setMapSize(self, length: int = ..., side: int = ...) -> None: ...
    img_player: Incomplete
    rect: Incomplete
    def setPlayerImage(self, imgPath) -> None: ...
    img_end: Incomplete
    oval: Incomplete
    def setEndImage(self, imgPath) -> None: ...
    def reset(self): ...
    def step(self, action): ...
    def render(self) -> None: ...
