# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from multinode.api_client.models.invocation_status import InvocationStatus
from multinode.api_client.models.parent_invocation_definition import ParentInvocationDefinition

class InvocationInfoForFunction(BaseModel):
    """
    InvocationInfoForFunction
    """
    invocation_id: StrictStr = Field(...)
    parent_invocation: Optional[ParentInvocationDefinition] = Field(...)
    cancellation_request_time: Optional[StrictInt] = Field(...)
    invocation_status: InvocationStatus = Field(...)
    creation_time: StrictInt = Field(...)
    last_update_time: StrictInt = Field(...)
    __properties = ["invocation_id", "parent_invocation", "cancellation_request_time", "invocation_status", "creation_time", "last_update_time"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> InvocationInfoForFunction:
        """Create an instance of InvocationInfoForFunction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of parent_invocation
        if self.parent_invocation:
            _dict['parent_invocation'] = self.parent_invocation.to_dict()
        # set to None if parent_invocation (nullable) is None
        # and __fields_set__ contains the field
        if self.parent_invocation is None and "parent_invocation" in self.__fields_set__:
            _dict['parent_invocation'] = None

        # set to None if cancellation_request_time (nullable) is None
        # and __fields_set__ contains the field
        if self.cancellation_request_time is None and "cancellation_request_time" in self.__fields_set__:
            _dict['cancellation_request_time'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> InvocationInfoForFunction:
        """Create an instance of InvocationInfoForFunction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return InvocationInfoForFunction.parse_obj(obj)

        _obj = InvocationInfoForFunction.parse_obj({
            "invocation_id": obj.get("invocation_id"),
            "parent_invocation": ParentInvocationDefinition.from_dict(obj.get("parent_invocation")) if obj.get("parent_invocation") is not None else None,
            "cancellation_request_time": obj.get("cancellation_request_time"),
            "invocation_status": obj.get("invocation_status"),
            "creation_time": obj.get("creation_time"),
            "last_update_time": obj.get("last_update_time")
        })
        return _obj


