"""
Python MCU Bootloader
~~~~~~~~~~~~~~~~~~~~~

pymdfu is a Python driver for a MCU bootloader
"""
import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())

# Build number part of version will be replaced by build number from Jenkins.
# For local builds the build number is 0 and the 'snapshot' is added as Local Version Identifier
__version__ = '0.1.4.4'

# The GIT commit ID and build date are generated by Jenkins when building the package
COMMIT_ID = '185babe0bd3bad887852ac2c10bf5ae31b00e858'
BUILD_DATE = '2023-10-30 13:44:49'

