
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-02T07:31:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "5951119d0ed125caad11b54b3dcad5bdeacafdbe",
 "version": "2023.11.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
