
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-02T13:38:21+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d69f589fcda9a78e6b927dc0111e2d048067da6",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
